// this file was generated by gomacro command: import "github.com/cosmos72/gomacro/scanner"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package scanner

import (
	. "reflect"
	"github.com/cosmos72/gomacro/imports"
)

func init() {
	imports.Packages["github.com/cosmos72/gomacro/scanner"] = imports.Package{
	Binds: map[string]Value{
		"PrintError":	ValueOf(PrintError),
		"ScanComments":	ValueOf(ScanComments),
	},
	Types: map[string]Type{
		"Error":	TypeOf((*Error)(nil)).Elem(),
		"ErrorHandler":	TypeOf((*ErrorHandler)(nil)).Elem(),
		"ErrorList":	TypeOf((*ErrorList)(nil)).Elem(),
		"Mode":	TypeOf((*Mode)(nil)).Elem(),
		"Scanner":	TypeOf((*Scanner)(nil)).Elem(),
	},
	Proxies: map[string]Type{
	} }
}
