// this file was generated by gomacro command: import "github.com/cosmos72/gomacro/parser"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package parser

import (
	r "reflect"

	"github.com/cosmos72/gomacro/imports"
)

// reflection: allow interpreted code to import "github.com/cosmos72/gomacro/parser"
func init() {
	imports.Packages["github.com/cosmos72/gomacro/parser"] = imports.Package{
		Binds: map[string]r.Value{
			"AllErrors":         r.ValueOf(AllErrors),
			"DeclarationErrors": r.ValueOf(DeclarationErrors),
			"ImportsOnly":       r.ValueOf(ImportsOnly),
			"PackageClauseOnly": r.ValueOf(PackageClauseOnly),
			"ParseComments":     r.ValueOf(ParseComments),
			"SpuriousErrors":    r.ValueOf(SpuriousErrors),
			"Trace":             r.ValueOf(Trace),
		},
		Types: map[string]r.Type{
			"Bailout": r.TypeOf((*bailout)(nil)).Elem(),
			"Mode":    r.TypeOf((*Mode)(nil)).Elem(),
			"Parser":  r.TypeOf((*Parser)(nil)).Elem(),
		},
		Proxies: map[string]r.Type{}}
}
