// this file was generated by gomacro command: import "github.com/cosmos72/gomacro/parser"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package parser

import (
	. "reflect"
	"github.com/cosmos72/gomacro/imports"
)

func init() {
	imports.Packages["github.com/cosmos72/gomacro/parser"] = imports.Package{
	Binds: map[string]Value{
		"AllErrors":	ValueOf(AllErrors),
		"DeclarationErrors":	ValueOf(DeclarationErrors),
		"ImportsOnly":	ValueOf(ImportsOnly),
		"PackageClauseOnly":	ValueOf(PackageClauseOnly),
		"ParseComments":	ValueOf(ParseComments),
		"SpuriousErrors":	ValueOf(SpuriousErrors),
		"Trace":	ValueOf(Trace),
	},
	Types: map[string]Type{
		"Bailout":	TypeOf((*Bailout)(nil)).Elem(),
		"Mode":	TypeOf((*Mode)(nil)).Elem(),
		"Parser":	TypeOf((*Parser)(nil)).Elem(),
	},
	Proxies: map[string]Type{
	} }
}
