// this file was generated by gomacro command: import "github.com/cosmos72/gomacro/ast2"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package reflection

import (
	"go/ast"
	"go/token"
	. "reflect"

	"github.com/cosmos72/gomacro/ast2"
	. "github.com/cosmos72/gomacro/imports"
)

// reflection: allow interpreted code to import "github.com/cosmos72/gomacro/ast2"
func init() {
	Packages["github.com/cosmos72/gomacro/ast2"] = Package{
		Binds: map[string]Value{
			"AnyToAst":          ValueOf(ast2.AnyToAst),
			"AnyToAstWithNode":  ValueOf(ast2.AnyToAstWithNode),
			"AnyToAstWithSlice": ValueOf(ast2.AnyToAstWithSlice),
			"BlockStmtToExpr":   ValueOf(ast2.BlockStmtToExpr),
			"ToAst":             ValueOf(ast2.ToAst),
			"ToAst1":            ValueOf(ast2.ToAst1),
			"ToAst2":            ValueOf(ast2.ToAst2),
			"ToAst3":            ValueOf(ast2.ToAst3),
			"ToAst4":            ValueOf(ast2.ToAst4),
			"ToAstWithSlice":    ValueOf(ast2.ToAstWithSlice),
			"ToBasicLit":        ValueOf(ast2.ToBasicLit),
			"ToBlockStmt":       ValueOf(ast2.ToBlockStmt),
			"ToCallExpr":        ValueOf(ast2.ToCallExpr),
			"ToDecl":            ValueOf(ast2.ToDecl),
			"ToExpr":            ValueOf(ast2.ToExpr),
			"ToExprSlice":       ValueOf(ast2.ToExprSlice),
			"ToField":           ValueOf(ast2.ToField),
			"ToFieldList":       ValueOf(ast2.ToFieldList),
			"ToFile":            ValueOf(ast2.ToFile),
			"ToFuncType":        ValueOf(ast2.ToFuncType),
			"ToIdent":           ValueOf(ast2.ToIdent),
			"ToIdentSlice":      ValueOf(ast2.ToIdentSlice),
			"ToImportSpec":      ValueOf(ast2.ToImportSpec),
			"ToNode":            ValueOf(ast2.ToNode),
			"ToSpec":            ValueOf(ast2.ToSpec),
			"ToStmt":            ValueOf(ast2.ToStmt),
			"ToStmtSlice":       ValueOf(ast2.ToStmtSlice),
		},
		Types: map[string]Type{
			"ArrayType":      TypeOf((*ast2.ArrayType)(nil)).Elem(),
			"AssignStmt":     TypeOf((*ast2.AssignStmt)(nil)).Elem(),
			"Ast":            TypeOf((*ast2.Ast)(nil)).Elem(),
			"AstWithNode":    TypeOf((*ast2.AstWithNode)(nil)).Elem(),
			"AstWithSlice":   TypeOf((*ast2.AstWithSlice)(nil)).Elem(),
			"BadDecl":        TypeOf((*ast2.BadDecl)(nil)).Elem(),
			"BadExpr":        TypeOf((*ast2.BadExpr)(nil)).Elem(),
			"BadStmt":        TypeOf((*ast2.BadStmt)(nil)).Elem(),
			"BasicLit":       TypeOf((*ast2.BasicLit)(nil)).Elem(),
			"BinaryExpr":     TypeOf((*ast2.BinaryExpr)(nil)).Elem(),
			"BlockStmt":      TypeOf((*ast2.BlockStmt)(nil)).Elem(),
			"BranchStmt":     TypeOf((*ast2.BranchStmt)(nil)).Elem(),
			"CallExpr":       TypeOf((*ast2.CallExpr)(nil)).Elem(),
			"CaseClause":     TypeOf((*ast2.CaseClause)(nil)).Elem(),
			"ChanType":       TypeOf((*ast2.ChanType)(nil)).Elem(),
			"CommClause":     TypeOf((*ast2.CommClause)(nil)).Elem(),
			"CompositeLit":   TypeOf((*ast2.CompositeLit)(nil)).Elem(),
			"DeclSlice":      TypeOf((*ast2.DeclSlice)(nil)).Elem(),
			"DeclStmt":       TypeOf((*ast2.DeclStmt)(nil)).Elem(),
			"DeferStmt":      TypeOf((*ast2.DeferStmt)(nil)).Elem(),
			"Ellipsis":       TypeOf((*ast2.Ellipsis)(nil)).Elem(),
			"EmptyStmt":      TypeOf((*ast2.EmptyStmt)(nil)).Elem(),
			"ExprSlice":      TypeOf((*ast2.ExprSlice)(nil)).Elem(),
			"ExprStmt":       TypeOf((*ast2.ExprStmt)(nil)).Elem(),
			"Field":          TypeOf((*ast2.Field)(nil)).Elem(),
			"FieldList":      TypeOf((*ast2.FieldList)(nil)).Elem(),
			"FieldSlice":     TypeOf((*ast2.FieldSlice)(nil)).Elem(),
			"File":           TypeOf((*ast2.File)(nil)).Elem(),
			"ForStmt":        TypeOf((*ast2.ForStmt)(nil)).Elem(),
			"FuncDecl":       TypeOf((*ast2.FuncDecl)(nil)).Elem(),
			"FuncLit":        TypeOf((*ast2.FuncLit)(nil)).Elem(),
			"FuncType":       TypeOf((*ast2.FuncType)(nil)).Elem(),
			"GenDecl":        TypeOf((*ast2.GenDecl)(nil)).Elem(),
			"GoStmt":         TypeOf((*ast2.GoStmt)(nil)).Elem(),
			"Ident":          TypeOf((*ast2.Ident)(nil)).Elem(),
			"IdentSlice":     TypeOf((*ast2.IdentSlice)(nil)).Elem(),
			"IfStmt":         TypeOf((*ast2.IfStmt)(nil)).Elem(),
			"ImportSpec":     TypeOf((*ast2.ImportSpec)(nil)).Elem(),
			"IncDecStmt":     TypeOf((*ast2.IncDecStmt)(nil)).Elem(),
			"IndexExpr":      TypeOf((*ast2.IndexExpr)(nil)).Elem(),
			"InterfaceType":  TypeOf((*ast2.InterfaceType)(nil)).Elem(),
			"KeyValueExpr":   TypeOf((*ast2.KeyValueExpr)(nil)).Elem(),
			"LabeledStmt":    TypeOf((*ast2.LabeledStmt)(nil)).Elem(),
			"MapType":        TypeOf((*ast2.MapType)(nil)).Elem(),
			"NodeSlice":      TypeOf((*ast2.NodeSlice)(nil)).Elem(),
			"Package":        TypeOf((*ast2.Package)(nil)).Elem(),
			"ParenExpr":      TypeOf((*ast2.ParenExpr)(nil)).Elem(),
			"RangeStmt":      TypeOf((*ast2.RangeStmt)(nil)).Elem(),
			"ReturnStmt":     TypeOf((*ast2.ReturnStmt)(nil)).Elem(),
			"SelectStmt":     TypeOf((*ast2.SelectStmt)(nil)).Elem(),
			"SelectorExpr":   TypeOf((*ast2.SelectorExpr)(nil)).Elem(),
			"SendStmt":       TypeOf((*ast2.SendStmt)(nil)).Elem(),
			"SliceExpr":      TypeOf((*ast2.SliceExpr)(nil)).Elem(),
			"SpecSlice":      TypeOf((*ast2.SpecSlice)(nil)).Elem(),
			"StarExpr":       TypeOf((*ast2.StarExpr)(nil)).Elem(),
			"StmtSlice":      TypeOf((*ast2.StmtSlice)(nil)).Elem(),
			"StructType":     TypeOf((*ast2.StructType)(nil)).Elem(),
			"SwitchStmt":     TypeOf((*ast2.SwitchStmt)(nil)).Elem(),
			"TypeAssertExpr": TypeOf((*ast2.TypeAssertExpr)(nil)).Elem(),
			"TypeSpec":       TypeOf((*ast2.TypeSpec)(nil)).Elem(),
			"TypeSwitchStmt": TypeOf((*ast2.TypeSwitchStmt)(nil)).Elem(),
			"UnaryExpr":      TypeOf((*ast2.UnaryExpr)(nil)).Elem(),
			"ValueSpec":      TypeOf((*ast2.ValueSpec)(nil)).Elem(),
		},
		Proxies: map[string]Type{
			"Ast":          TypeOf((*Ast_github_com_cosmos72_gomacro_ast2)(nil)).Elem(),
			"AstWithNode":  TypeOf((*AstWithNode_github_com_cosmos72_gomacro_ast2)(nil)).Elem(),
			"AstWithSlice": TypeOf((*AstWithSlice_github_com_cosmos72_gomacro_ast2)(nil)).Elem(),
		}}
}

// --------------- proxy for github.com/cosmos72/gomacro/ast2.Ast ---------------
type Ast_github_com_cosmos72_gomacro_ast2 struct {
	Object     interface{}
	Get_       func(i int) ast2.Ast
	Interface_ func() interface{}
	New_       func() ast2.Ast
	Op_        func() token.Token
	Set_       func(i int, child ast2.Ast)
	Size_      func() int
}

func (Proxy Ast_github_com_cosmos72_gomacro_ast2) Get(i int) ast2.Ast {
	return Proxy.Get_(i)
}
func (Proxy Ast_github_com_cosmos72_gomacro_ast2) Interface() interface{} {
	return Proxy.Interface_()
}
func (Proxy Ast_github_com_cosmos72_gomacro_ast2) New() ast2.Ast {
	return Proxy.New_()
}
func (Proxy Ast_github_com_cosmos72_gomacro_ast2) Op() token.Token {
	return Proxy.Op_()
}
func (Proxy Ast_github_com_cosmos72_gomacro_ast2) Set(i int, child ast2.Ast) {
	Proxy.Set_(i, child)
}
func (Proxy Ast_github_com_cosmos72_gomacro_ast2) Size() int {
	return Proxy.Size_()
}

// --------------- proxy for github.com/cosmos72/gomacro/ast2.AstWithNode ---------------
type AstWithNode_github_com_cosmos72_gomacro_ast2 struct {
	Object     interface{}
	Get_       func(i int) ast2.Ast
	Interface_ func() interface{}
	New_       func() ast2.Ast
	Node_      func() ast.Node
	Op_        func() token.Token
	Set_       func(i int, child ast2.Ast)
	Size_      func() int
}

func (Proxy AstWithNode_github_com_cosmos72_gomacro_ast2) Get(i int) ast2.Ast {
	return Proxy.Get_(i)
}
func (Proxy AstWithNode_github_com_cosmos72_gomacro_ast2) Interface() interface{} {
	return Proxy.Interface_()
}
func (Proxy AstWithNode_github_com_cosmos72_gomacro_ast2) New() ast2.Ast {
	return Proxy.New_()
}
func (Proxy AstWithNode_github_com_cosmos72_gomacro_ast2) Node() ast.Node {
	return Proxy.Node_()
}
func (Proxy AstWithNode_github_com_cosmos72_gomacro_ast2) Op() token.Token {
	return Proxy.Op_()
}
func (Proxy AstWithNode_github_com_cosmos72_gomacro_ast2) Set(i int, child ast2.Ast) {
	Proxy.Set_(i, child)
}
func (Proxy AstWithNode_github_com_cosmos72_gomacro_ast2) Size() int {
	return Proxy.Size_()
}

// --------------- proxy for github.com/cosmos72/gomacro/ast2.AstWithSlice ---------------
type AstWithSlice_github_com_cosmos72_gomacro_ast2 struct {
	Object     interface{}
	Append_    func(child ast2.Ast) ast2.AstWithSlice
	Get_       func(i int) ast2.Ast
	Interface_ func() interface{}
	New_       func() ast2.Ast
	Op_        func() token.Token
	Set_       func(i int, child ast2.Ast)
	Size_      func() int
	Slice_     func(lo int, hi int) ast2.AstWithSlice
}

func (Proxy AstWithSlice_github_com_cosmos72_gomacro_ast2) Append(child ast2.Ast) ast2.AstWithSlice {
	return Proxy.Append_(child)
}
func (Proxy AstWithSlice_github_com_cosmos72_gomacro_ast2) Get(i int) ast2.Ast {
	return Proxy.Get_(i)
}
func (Proxy AstWithSlice_github_com_cosmos72_gomacro_ast2) Interface() interface{} {
	return Proxy.Interface_()
}
func (Proxy AstWithSlice_github_com_cosmos72_gomacro_ast2) New() ast2.Ast {
	return Proxy.New_()
}
func (Proxy AstWithSlice_github_com_cosmos72_gomacro_ast2) Op() token.Token {
	return Proxy.Op_()
}
func (Proxy AstWithSlice_github_com_cosmos72_gomacro_ast2) Set(i int, child ast2.Ast) {
	Proxy.Set_(i, child)
}
func (Proxy AstWithSlice_github_com_cosmos72_gomacro_ast2) Size() int {
	return Proxy.Size_()
}
func (Proxy AstWithSlice_github_com_cosmos72_gomacro_ast2) Slice(lo int, hi int) ast2.AstWithSlice {
	return Proxy.Slice_(lo, hi)
}
