// this file was generated by gomacro command: import "github.com/cosmos72/gomacro/reflection"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package reflection

import (
	. "reflect"

	. "github.com/cosmos72/gomacro/imports"
)

// reflection: allow interpreted code to import "github.com/cosmos72/gomacro/reflection"
func init() {
	Packages["github.com/cosmos72/gomacro/reflection"] = Package{
		Binds:   map[string]Value{},
		Types:   map[string]Type{},
		Proxies: map[string]Type{}}
}
