// this file was generated by gomacro command: import "github.com/cosmos72/gomacro/scanner"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package reflection

import (
	. "reflect"

	. "github.com/cosmos72/gomacro/imports"
	"github.com/cosmos72/gomacro/scanner"
)

// reflection: allow interpreted code to import "github.com/cosmos72/gomacro/scanner"
func init() {
	Packages["github.com/cosmos72/gomacro/scanner"] = Package{
		Binds: map[string]Value{
			"PrintError":   ValueOf(scanner.PrintError),
			"ScanComments": ValueOf(scanner.ScanComments),
		},
		Types: map[string]Type{
			"Error":        TypeOf((*scanner.Error)(nil)).Elem(),
			"ErrorHandler": TypeOf((*scanner.ErrorHandler)(nil)).Elem(),
			"ErrorList":    TypeOf((*scanner.ErrorList)(nil)).Elem(),
			"Mode":         TypeOf((*scanner.Mode)(nil)).Elem(),
			"Scanner":      TypeOf((*scanner.Scanner)(nil)).Elem(),
		},
		Proxies: map[string]Type{}}
}
