// this file was generated by gomacro command: import "github.com/cosmos72/gomacro/token"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package reflection

import (
	. "reflect"

	. "github.com/cosmos72/gomacro/imports"
	"github.com/cosmos72/gomacro/token"
)

// reflection: allow interpreted code to import "github.com/cosmos72/gomacro/token"
func init() {
	Packages["github.com/cosmos72/gomacro/token"] = Package{
		Binds: map[string]Value{
			"INTERPRET_ONLY": ValueOf(token.INTERPRET_ONLY),
			"IsKeyword":      ValueOf(token.IsKeyword),
			"IsLiteral":      ValueOf(token.IsLiteral),
			"IsMacroKeyword": ValueOf(token.IsMacroKeyword),
			"IsOperator":     ValueOf(token.IsOperator),
			"Lookup":         ValueOf(token.Lookup),
			"MACRO":          ValueOf(token.MACRO),
			"QUASIQUOTE":     ValueOf(token.QUASIQUOTE),
			"QUOTE":          ValueOf(token.QUOTE),
			"SPLICE":         ValueOf(token.SPLICE),
			"String":         ValueOf(token.String),
			"UNQUOTE":        ValueOf(token.UNQUOTE),
			"UNQUOTE_SPLICE": ValueOf(token.UNQUOTE_SPLICE),
		},
		Types:   map[string]Type{},
		Proxies: map[string]Type{}}
}
