// this file was generated by gomacro command: import "archive/zip"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	"archive/zip"
)

func init() {
	Binds["archive/zip"] = map[string]Value{
		"Deflate":	ValueOf(zip.Deflate),
		"ErrAlgorithm":	ValueOf(&zip.ErrAlgorithm).Elem(),
		"ErrChecksum":	ValueOf(&zip.ErrChecksum).Elem(),
		"ErrFormat":	ValueOf(&zip.ErrFormat).Elem(),
		"FileInfoHeader":	ValueOf(zip.FileInfoHeader),
		"NewReader":	ValueOf(zip.NewReader),
		"NewWriter":	ValueOf(zip.NewWriter),
		"OpenReader":	ValueOf(zip.OpenReader),
		"RegisterCompressor":	ValueOf(zip.RegisterCompressor),
		"RegisterDecompressor":	ValueOf(zip.RegisterDecompressor),
		"Store":	ValueOf(zip.Store),
	}
	Types["archive/zip"] = map[string]Type{
		"Compressor":	TypeOf((*zip.Compressor)(nil)).Elem(),
		"Decompressor":	TypeOf((*zip.Decompressor)(nil)).Elem(),
		"File":	TypeOf((*zip.File)(nil)).Elem(),
		"FileHeader":	TypeOf((*zip.FileHeader)(nil)).Elem(),
		"ReadCloser":	TypeOf((*zip.ReadCloser)(nil)).Elem(),
		"Reader":	TypeOf((*zip.Reader)(nil)).Elem(),
		"Writer":	TypeOf((*zip.Writer)(nil)).Elem(),
	}
	Proxies["archive/zip"] = map[string]Type{
	}
}
