// this file was generated by gomacro command: import "archive/zip"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "archive/zip"
	. "reflect"
)

func init() {
	Binds["archive/zip"] = map[string]Value{
		"Deflate":	ValueOf(pkg.Deflate),
		"ErrAlgorithm":	ValueOf(&pkg.ErrAlgorithm).Elem(),
		"ErrChecksum":	ValueOf(&pkg.ErrChecksum).Elem(),
		"ErrFormat":	ValueOf(&pkg.ErrFormat).Elem(),
		"FileInfoHeader":	ValueOf(pkg.FileInfoHeader),
		"NewReader":	ValueOf(pkg.NewReader),
		"NewWriter":	ValueOf(pkg.NewWriter),
		"OpenReader":	ValueOf(pkg.OpenReader),
		"RegisterCompressor":	ValueOf(pkg.RegisterCompressor),
		"RegisterDecompressor":	ValueOf(pkg.RegisterDecompressor),
		"Store":	ValueOf(pkg.Store),
	}
	Types["archive/zip"] = map[string]Type{
		"Compressor":	TypeOf((*pkg.Compressor)(nil)).Elem(),
		"Decompressor":	TypeOf((*pkg.Decompressor)(nil)).Elem(),
		"File":	TypeOf((*pkg.File)(nil)).Elem(),
		"FileHeader":	TypeOf((*pkg.FileHeader)(nil)).Elem(),
		"ReadCloser":	TypeOf((*pkg.ReadCloser)(nil)).Elem(),
		"Reader":	TypeOf((*pkg.Reader)(nil)).Elem(),
		"Writer":	TypeOf((*pkg.Writer)(nil)).Elem(),
	}
}
