// this file was generated by gomacro command: import "archive/tar"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	"archive/tar"
)

func init() {
	Binds["archive/tar"] = map[string]Value{
		"ErrFieldTooLong":	ValueOf(&tar.ErrFieldTooLong).Elem(),
		"ErrHeader":	ValueOf(&tar.ErrHeader).Elem(),
		"ErrWriteAfterClose":	ValueOf(&tar.ErrWriteAfterClose).Elem(),
		"ErrWriteTooLong":	ValueOf(&tar.ErrWriteTooLong).Elem(),
		"FileInfoHeader":	ValueOf(tar.FileInfoHeader),
		"NewReader":	ValueOf(tar.NewReader),
		"NewWriter":	ValueOf(tar.NewWriter),
		"TypeBlock":	ValueOf(tar.TypeBlock),
		"TypeChar":	ValueOf(tar.TypeChar),
		"TypeCont":	ValueOf(tar.TypeCont),
		"TypeDir":	ValueOf(tar.TypeDir),
		"TypeFifo":	ValueOf(tar.TypeFifo),
		"TypeGNULongLink":	ValueOf(tar.TypeGNULongLink),
		"TypeGNULongName":	ValueOf(tar.TypeGNULongName),
		"TypeGNUSparse":	ValueOf(tar.TypeGNUSparse),
		"TypeLink":	ValueOf(tar.TypeLink),
		"TypeReg":	ValueOf(tar.TypeReg),
		"TypeRegA":	ValueOf(tar.TypeRegA),
		"TypeSymlink":	ValueOf(tar.TypeSymlink),
		"TypeXGlobalHeader":	ValueOf(tar.TypeXGlobalHeader),
		"TypeXHeader":	ValueOf(tar.TypeXHeader),
	}
	Types["archive/tar"] = map[string]Type{
		"Header":	TypeOf((*tar.Header)(nil)).Elem(),
		"Reader":	TypeOf((*tar.Reader)(nil)).Elem(),
		"Writer":	TypeOf((*tar.Writer)(nil)).Elem(),
	}
	Proxies["archive/tar"] = map[string]Type{
	}
}
