// this file was generated by gomacro command: import "bufio"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	"bufio"
)

func init() {
	Binds["bufio"] = map[string]Value{
		"ErrAdvanceTooFar":	ValueOf(&bufio.ErrAdvanceTooFar).Elem(),
		"ErrBufferFull":	ValueOf(&bufio.ErrBufferFull).Elem(),
		"ErrFinalToken":	ValueOf(&bufio.ErrFinalToken).Elem(),
		"ErrInvalidUnreadByte":	ValueOf(&bufio.ErrInvalidUnreadByte).Elem(),
		"ErrInvalidUnreadRune":	ValueOf(&bufio.ErrInvalidUnreadRune).Elem(),
		"ErrNegativeAdvance":	ValueOf(&bufio.ErrNegativeAdvance).Elem(),
		"ErrNegativeCount":	ValueOf(&bufio.ErrNegativeCount).Elem(),
		"ErrTooLong":	ValueOf(&bufio.ErrTooLong).Elem(),
		"MaxScanTokenSize":	ValueOf(bufio.MaxScanTokenSize),
		"NewReadWriter":	ValueOf(bufio.NewReadWriter),
		"NewReader":	ValueOf(bufio.NewReader),
		"NewReaderSize":	ValueOf(bufio.NewReaderSize),
		"NewScanner":	ValueOf(bufio.NewScanner),
		"NewWriter":	ValueOf(bufio.NewWriter),
		"NewWriterSize":	ValueOf(bufio.NewWriterSize),
		"ScanBytes":	ValueOf(bufio.ScanBytes),
		"ScanLines":	ValueOf(bufio.ScanLines),
		"ScanRunes":	ValueOf(bufio.ScanRunes),
		"ScanWords":	ValueOf(bufio.ScanWords),
	}
	Types["bufio"] = map[string]Type{
		"ReadWriter":	TypeOf((*bufio.ReadWriter)(nil)).Elem(),
		"Reader":	TypeOf((*bufio.Reader)(nil)).Elem(),
		"Scanner":	TypeOf((*bufio.Scanner)(nil)).Elem(),
		"SplitFunc":	TypeOf((*bufio.SplitFunc)(nil)).Elem(),
		"Writer":	TypeOf((*bufio.Writer)(nil)).Elem(),
	}
	Proxies["bufio"] = map[string]Type{
	}
}
