// this file was generated by gomacro command: import _b "compress/bzip2"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	bzip2 "compress/bzip2"
)

// reflection: allow interpreted code to import "compress/bzip2"
func init() {
	Packages["compress/bzip2"] = Package{
	Name: "bzip2",
	Binds: map[string]Value{
		"NewReader":	ValueOf(bzip2.NewReader),
	}, Types: map[string]Type{
		"StructuralError":	TypeOf((*bzip2.StructuralError)(nil)).Elem(),
	}, 
	}
}
