// this file was generated by gomacro command: import "compress/lzw"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "compress/lzw"
	. "reflect"
)

func init() {
	Binds["compress/lzw"] = map[string]Value{
		"LSB":	ValueOf(pkg.LSB),
		"MSB":	ValueOf(pkg.MSB),
		"NewReader":	ValueOf(pkg.NewReader),
		"NewWriter":	ValueOf(pkg.NewWriter),
	}
	Types["compress/lzw"] = map[string]Type{
		"Order":	TypeOf((*pkg.Order)(nil)).Elem(),
	}
}
