// this file was generated by gomacro command: import "compress/bzip2"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "compress/bzip2"
	. "reflect"
)

func Package_compress_bzip2() (map[string]Value, map[string]Type) {
	return map[string]Value{
			"NewReader": ValueOf(pkg.NewReader),
		}, map[string]Type{
			"StructuralError": TypeOf((*pkg.StructuralError)(nil)).Elem(),
		}
}

func init() {
	binds, types := Package_compress_bzip2()
	Binds["compress/bzip2"] = binds
	Types["compress/bzip2"] = types
}
