// this file was generated by gomacro command: import "compress/lzw"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "compress/lzw"
	. "reflect"
)

func Package_compress_lzw() (map[string]Value, map[string]Type) {
	return map[string]Value{
			"LSB":       ValueOf(pkg.LSB),
			"MSB":       ValueOf(pkg.MSB),
			"NewReader": ValueOf(pkg.NewReader),
			"NewWriter": ValueOf(pkg.NewWriter),
		}, map[string]Type{
			"Order": TypeOf((*pkg.Order)(nil)).Elem(),
		}
}

func init() {
	binds, types := Package_compress_lzw()
	Binds["compress/lzw"] = binds
	Types["compress/lzw"] = types
}
