// this file was generated by gomacro command: import "container/list"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "container/list"
	. "reflect"
)

func Package_container_list() (map[string]Value, map[string]Type) {
	return map[string]Value{
			"New": ValueOf(pkg.New),
		}, map[string]Type{
			"Element": TypeOf((*pkg.Element)(nil)).Elem(),
			"List":    TypeOf((*pkg.List)(nil)).Elem(),
		}
}

func init() {
	binds, types := Package_container_list()
	Binds["container/list"] = binds
	Types["container/list"] = types
}
