// this file was generated by gomacro command: import "container/heap"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "container/heap"
	. "reflect"
)

func init() {
	Binds["container/heap"] = map[string]Value{
		"Fix":	ValueOf(pkg.Fix),
		"Init":	ValueOf(pkg.Init),
		"Pop":	ValueOf(pkg.Pop),
		"Push":	ValueOf(pkg.Push),
		"Remove":	ValueOf(pkg.Remove),
	}
	Types["container/heap"] = map[string]Type{
		"Interface":	TypeOf((*pkg.Interface)(nil)).Elem(),
	}
}
