// this file was generated by gomacro command: import _b "container/ring"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	ring "container/ring"
)

// reflection: allow interpreted code to import "container/ring"
func init() {
	Packages["container/ring"] = Package{
	Name: "ring",
	Binds: map[string]Value{
		"New":	ValueOf(ring.New),
	}, Types: map[string]Type{
		"Ring":	TypeOf((*ring.Ring)(nil)).Elem(),
	}, 
	}
}
