// this file was generated by gomacro command: import "container/ring"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "container/ring"
	. "reflect"
)

func Package_container_ring() (map[string]Value, map[string]Type) {
	return map[string]Value{
			"New": ValueOf(pkg.New),
		}, map[string]Type{
			"Ring": TypeOf((*pkg.Ring)(nil)).Elem(),
		}
}

func init() {
	binds, types := Package_container_ring()
	Binds["container/ring"] = binds
	Types["container/ring"] = types
}
