// this file was generated by gomacro command: import "container/list"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "container/list"
	. "reflect"
)

func init() {
	Binds["container/list"] = map[string]Value{
		"New":	ValueOf(pkg.New),
	}
	Types["container/list"] = map[string]Type{
		"Element":	TypeOf((*pkg.Element)(nil)).Elem(),
		"List":	TypeOf((*pkg.List)(nil)).Elem(),
	}
}
