// this file was generated by gomacro command: import "crypto"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "crypto"
	. "reflect"
)

func init() {
	Binds["crypto"] = map[string]Value{
		"MD4":	ValueOf(pkg.MD4),
		"MD5":	ValueOf(pkg.MD5),
		"MD5SHA1":	ValueOf(pkg.MD5SHA1),
		"RIPEMD160":	ValueOf(pkg.RIPEMD160),
		"RegisterHash":	ValueOf(pkg.RegisterHash),
		"SHA1":	ValueOf(pkg.SHA1),
		"SHA224":	ValueOf(pkg.SHA224),
		"SHA256":	ValueOf(pkg.SHA256),
		"SHA384":	ValueOf(pkg.SHA384),
		"SHA3_224":	ValueOf(pkg.SHA3_224),
		"SHA3_256":	ValueOf(pkg.SHA3_256),
		"SHA3_384":	ValueOf(pkg.SHA3_384),
		"SHA3_512":	ValueOf(pkg.SHA3_512),
		"SHA512":	ValueOf(pkg.SHA512),
		"SHA512_224":	ValueOf(pkg.SHA512_224),
		"SHA512_256":	ValueOf(pkg.SHA512_256),
	}
	Types["crypto"] = map[string]Type{
		"Decrypter":	TypeOf((*pkg.Decrypter)(nil)).Elem(),
		"DecrypterOpts":	TypeOf((*pkg.DecrypterOpts)(nil)).Elem(),
		"Hash":	TypeOf((*pkg.Hash)(nil)).Elem(),
		"PrivateKey":	TypeOf((*pkg.PrivateKey)(nil)).Elem(),
		"PublicKey":	TypeOf((*pkg.PublicKey)(nil)).Elem(),
		"Signer":	TypeOf((*pkg.Signer)(nil)).Elem(),
		"SignerOpts":	TypeOf((*pkg.SignerOpts)(nil)).Elem(),
	}
}
