// this file was generated by gomacro command: import "crypto/sha1"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "crypto/sha1"
	. "reflect"
)

func init() {
	Binds["crypto/sha1"] = map[string]Value{
		"BlockSize":	ValueOf(pkg.BlockSize),
		"New":	ValueOf(pkg.New),
		"Size":	ValueOf(pkg.Size),
		"Sum":	ValueOf(pkg.Sum),
	}
	Types["crypto/sha1"] = map[string]Type{
	}
}
