// this file was generated by gomacro command: import "crypto/rc4"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	"crypto/rc4"
)

func init() {
	Binds["crypto/rc4"] = map[string]Value{
		"NewCipher":	ValueOf(rc4.NewCipher),
	}
	Types["crypto/rc4"] = map[string]Type{
		"Cipher":	TypeOf((*rc4.Cipher)(nil)).Elem(),
		"KeySizeError":	TypeOf((*rc4.KeySizeError)(nil)).Elem(),
	}
	Proxies["crypto/rc4"] = map[string]Type{
	}
}
