// this file was generated by gomacro command: import "crypto/x509/pkix"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "crypto/x509/pkix"
	. "reflect"
)

func Package_crypto_x509_pkix() (map[string]Value, map[string]Type) {
	return map[string]Value{}, map[string]Type{
			"AlgorithmIdentifier":          TypeOf((*pkg.AlgorithmIdentifier)(nil)).Elem(),
			"AttributeTypeAndValue":        TypeOf((*pkg.AttributeTypeAndValue)(nil)).Elem(),
			"AttributeTypeAndValueSET":     TypeOf((*pkg.AttributeTypeAndValueSET)(nil)).Elem(),
			"CertificateList":              TypeOf((*pkg.CertificateList)(nil)).Elem(),
			"Extension":                    TypeOf((*pkg.Extension)(nil)).Elem(),
			"Name":                         TypeOf((*pkg.Name)(nil)).Elem(),
			"RDNSequence":                  TypeOf((*pkg.RDNSequence)(nil)).Elem(),
			"RelativeDistinguishedNameSET": TypeOf((*pkg.RelativeDistinguishedNameSET)(nil)).Elem(),
			"RevokedCertificate":           TypeOf((*pkg.RevokedCertificate)(nil)).Elem(),
			"TBSCertificateList":           TypeOf((*pkg.TBSCertificateList)(nil)).Elem(),
		}
}

func init() {
	binds, types := Package_crypto_x509_pkix()
	Binds["crypto/x509/pkix"] = binds
	Types["crypto/x509/pkix"] = types
}
