// this file was generated by gomacro command: import "crypto/sha256"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "crypto/sha256"
	. "reflect"
)

func init() {
	Binds["crypto/sha256"] = map[string]Value{
		"BlockSize":	ValueOf(pkg.BlockSize),
		"New":	ValueOf(pkg.New),
		"New224":	ValueOf(pkg.New224),
		"Size":	ValueOf(pkg.Size),
		"Size224":	ValueOf(pkg.Size224),
		"Sum224":	ValueOf(pkg.Sum224),
		"Sum256":	ValueOf(pkg.Sum256),
	}
	Types["crypto/sha256"] = map[string]Type{
	}
}
