// this file was generated by gomacro command: import "crypto/ecdsa"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "crypto/ecdsa"
	. "reflect"
)

func init() {
	Binds["crypto/ecdsa"] = map[string]Value{
		"GenerateKey":	ValueOf(pkg.GenerateKey),
		"Sign":	ValueOf(pkg.Sign),
		"Verify":	ValueOf(pkg.Verify),
	}
	Types["crypto/ecdsa"] = map[string]Type{
		"PrivateKey":	TypeOf((*pkg.PrivateKey)(nil)).Elem(),
		"PublicKey":	TypeOf((*pkg.PublicKey)(nil)).Elem(),
	}
}
