// this file was generated by gomacro command: import "crypto/rand"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "crypto/rand"
	. "reflect"
)

func init() {
	Binds["crypto/rand"] = map[string]Value{
		"Int":	ValueOf(pkg.Int),
		"Prime":	ValueOf(pkg.Prime),
		"Read":	ValueOf(pkg.Read),
		"Reader":	ValueOf(&pkg.Reader).Elem(),
	}
	Types["crypto/rand"] = map[string]Type{
	}
}
