// this file was generated by gomacro command: import "crypto/sha1"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	"crypto/sha1"
)

func init() {
	Binds["crypto/sha1"] = map[string]Value{
		"BlockSize":	ValueOf(sha1.BlockSize),
		"New":	ValueOf(sha1.New),
		"Size":	ValueOf(sha1.Size),
		"Sum":	ValueOf(sha1.Sum),
	}
	Types["crypto/sha1"] = map[string]Type{
	}
	Proxies["crypto/sha1"] = map[string]Type{
	}
}
