// this file was generated by gomacro command: import "crypto/rsa"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "crypto/rsa"
	. "reflect"
)

func init() {
	Binds["crypto/rsa"] = map[string]Value{
		"DecryptOAEP":	ValueOf(pkg.DecryptOAEP),
		"DecryptPKCS1v15":	ValueOf(pkg.DecryptPKCS1v15),
		"DecryptPKCS1v15SessionKey":	ValueOf(pkg.DecryptPKCS1v15SessionKey),
		"EncryptOAEP":	ValueOf(pkg.EncryptOAEP),
		"EncryptPKCS1v15":	ValueOf(pkg.EncryptPKCS1v15),
		"ErrDecryption":	ValueOf(&pkg.ErrDecryption).Elem(),
		"ErrMessageTooLong":	ValueOf(&pkg.ErrMessageTooLong).Elem(),
		"ErrVerification":	ValueOf(&pkg.ErrVerification).Elem(),
		"GenerateKey":	ValueOf(pkg.GenerateKey),
		"GenerateMultiPrimeKey":	ValueOf(pkg.GenerateMultiPrimeKey),
		"PSSSaltLengthAuto":	ValueOf(pkg.PSSSaltLengthAuto),
		"PSSSaltLengthEqualsHash":	ValueOf(pkg.PSSSaltLengthEqualsHash),
		"SignPKCS1v15":	ValueOf(pkg.SignPKCS1v15),
		"SignPSS":	ValueOf(pkg.SignPSS),
		"VerifyPKCS1v15":	ValueOf(pkg.VerifyPKCS1v15),
		"VerifyPSS":	ValueOf(pkg.VerifyPSS),
	}
	Types["crypto/rsa"] = map[string]Type{
		"CRTValue":	TypeOf((*pkg.CRTValue)(nil)).Elem(),
		"OAEPOptions":	TypeOf((*pkg.OAEPOptions)(nil)).Elem(),
		"PKCS1v15DecryptOptions":	TypeOf((*pkg.PKCS1v15DecryptOptions)(nil)).Elem(),
		"PSSOptions":	TypeOf((*pkg.PSSOptions)(nil)).Elem(),
		"PrecomputedValues":	TypeOf((*pkg.PrecomputedValues)(nil)).Elem(),
		"PrivateKey":	TypeOf((*pkg.PrivateKey)(nil)).Elem(),
		"PublicKey":	TypeOf((*pkg.PublicKey)(nil)).Elem(),
	}
}
