// this file was generated by gomacro command: import "crypto/hmac"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	"crypto/hmac"
)

func init() {
	Packages["crypto/hmac"] = Package{
	Binds: map[string]Value{
		"Equal":	ValueOf(hmac.Equal),
		"New":	ValueOf(hmac.New),
	},
	Types: map[string]Type{
	},
	Proxies: map[string]Type{
	} }
}
