// this file was generated by gomacro command: import "crypto/des"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "crypto/des"
	. "reflect"
)

func init() {
	Binds["crypto/des"] = map[string]Value{
		"BlockSize":	ValueOf(pkg.BlockSize),
		"NewCipher":	ValueOf(pkg.NewCipher),
		"NewTripleDESCipher":	ValueOf(pkg.NewTripleDESCipher),
	}
	Types["crypto/des"] = map[string]Type{
		"KeySizeError":	TypeOf((*pkg.KeySizeError)(nil)).Elem(),
	}
}
