// this file was generated by gomacro command: import "crypto/des"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "crypto/des"
	. "reflect"
)

func Package_crypto_des() (map[string]Value, map[string]Type) {
	return map[string]Value{
			"BlockSize":          ValueOf(pkg.BlockSize),
			"NewCipher":          ValueOf(pkg.NewCipher),
			"NewTripleDESCipher": ValueOf(pkg.NewTripleDESCipher),
		}, map[string]Type{
			"KeySizeError": TypeOf((*pkg.KeySizeError)(nil)).Elem(),
		}
}

func init() {
	binds, types := Package_crypto_des()
	Binds["crypto/des"] = binds
	Types["crypto/des"] = types
}
