// this file was generated by gomacro command: import _b "crypto/aes"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	aes "crypto/aes"
)

// reflection: allow interpreted code to import "crypto/aes"
func init() {
	Packages["crypto/aes"] = Package{
	Name: "aes",
	Binds: map[string]Value{
		"BlockSize":	ValueOf(aes.BlockSize),
		"NewCipher":	ValueOf(aes.NewCipher),
	}, Types: map[string]Type{
		"KeySizeError":	TypeOf((*aes.KeySizeError)(nil)).Elem(),
	}, Untypeds: map[string]string{
		"BlockSize":	"int:16",
	}, 
	}
}
