// this file was generated by gomacro command: import "crypto/md5"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "crypto/md5"
	. "reflect"
)

func Package_crypto_md5() (map[string]Value, map[string]Type) {
	return map[string]Value{
			"BlockSize": ValueOf(pkg.BlockSize),
			"New":       ValueOf(pkg.New),
			"Size":      ValueOf(pkg.Size),
			"Sum":       ValueOf(pkg.Sum),
		}, map[string]Type{}
}

func init() {
	binds, types := Package_crypto_md5()
	Binds["crypto/md5"] = binds
	Types["crypto/md5"] = types
}
