// this file was generated by gomacro command: import "crypto/hmac"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "crypto/hmac"
	. "reflect"
)

func init() {
	Binds["crypto/hmac"] = map[string]Value{
		"Equal":	ValueOf(pkg.Equal),
		"New":	ValueOf(pkg.New),
	}
	Types["crypto/hmac"] = map[string]Type{
	}
}
