// this file was generated by gomacro command: import _b "crypto/ecdsa"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	"crypto/ecdsa"
	. "reflect"
)

// reflection: allow interpreted code to import "crypto/ecdsa"
func init() {
	Packages["crypto/ecdsa"] = Package{
		Binds: map[string]Value{
			"GenerateKey": ValueOf(ecdsa.GenerateKey),
			"Sign":        ValueOf(ecdsa.Sign),
			"Verify":      ValueOf(ecdsa.Verify),
		}, Types: map[string]Type{
			"PrivateKey": TypeOf((*ecdsa.PrivateKey)(nil)).Elem(),
			"PublicKey":  TypeOf((*ecdsa.PublicKey)(nil)).Elem(),
		},
	}
}
