// this file was generated by gomacro command: import "crypto/aes"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "crypto/aes"
	. "reflect"
)

func Package_crypto_aes() (map[string]Value, map[string]Type) {
	return map[string]Value{
			"BlockSize": ValueOf(pkg.BlockSize),
			"NewCipher": ValueOf(pkg.NewCipher),
		}, map[string]Type{
			"KeySizeError": TypeOf((*pkg.KeySizeError)(nil)).Elem(),
		}
}

func init() {
	binds, types := Package_crypto_aes()
	Binds["crypto/aes"] = binds
	Types["crypto/aes"] = types
}
