// this file was generated by gomacro command: import "database/sql/driver"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "database/sql/driver"
	. "reflect"
)

func init() {
	Binds["database/sql/driver"] = map[string]Value{
		"Bool":	ValueOf(&pkg.Bool).Elem(),
		"DefaultParameterConverter":	ValueOf(&pkg.DefaultParameterConverter).Elem(),
		"ErrBadConn":	ValueOf(&pkg.ErrBadConn).Elem(),
		"ErrSkip":	ValueOf(&pkg.ErrSkip).Elem(),
		"Int32":	ValueOf(&pkg.Int32).Elem(),
		"IsScanValue":	ValueOf(pkg.IsScanValue),
		"IsValue":	ValueOf(pkg.IsValue),
		"ResultNoRows":	ValueOf(&pkg.ResultNoRows).Elem(),
		"String":	ValueOf(&pkg.String).Elem(),
	}
	Types["database/sql/driver"] = map[string]Type{
		"ColumnConverter":	TypeOf((*pkg.ColumnConverter)(nil)).Elem(),
		"Conn":	TypeOf((*pkg.Conn)(nil)).Elem(),
		"ConnBeginTx":	TypeOf((*pkg.ConnBeginTx)(nil)).Elem(),
		"ConnPrepareContext":	TypeOf((*pkg.ConnPrepareContext)(nil)).Elem(),
		"Driver":	TypeOf((*pkg.Driver)(nil)).Elem(),
		"Execer":	TypeOf((*pkg.Execer)(nil)).Elem(),
		"ExecerContext":	TypeOf((*pkg.ExecerContext)(nil)).Elem(),
		"IsolationLevel":	TypeOf((*pkg.IsolationLevel)(nil)).Elem(),
		"NamedValue":	TypeOf((*pkg.NamedValue)(nil)).Elem(),
		"NotNull":	TypeOf((*pkg.NotNull)(nil)).Elem(),
		"Null":	TypeOf((*pkg.Null)(nil)).Elem(),
		"Pinger":	TypeOf((*pkg.Pinger)(nil)).Elem(),
		"Queryer":	TypeOf((*pkg.Queryer)(nil)).Elem(),
		"QueryerContext":	TypeOf((*pkg.QueryerContext)(nil)).Elem(),
		"Result":	TypeOf((*pkg.Result)(nil)).Elem(),
		"Rows":	TypeOf((*pkg.Rows)(nil)).Elem(),
		"RowsAffected":	TypeOf((*pkg.RowsAffected)(nil)).Elem(),
		"RowsColumnTypeDatabaseTypeName":	TypeOf((*pkg.RowsColumnTypeDatabaseTypeName)(nil)).Elem(),
		"RowsColumnTypeLength":	TypeOf((*pkg.RowsColumnTypeLength)(nil)).Elem(),
		"RowsColumnTypeNullable":	TypeOf((*pkg.RowsColumnTypeNullable)(nil)).Elem(),
		"RowsColumnTypePrecisionScale":	TypeOf((*pkg.RowsColumnTypePrecisionScale)(nil)).Elem(),
		"RowsColumnTypeScanType":	TypeOf((*pkg.RowsColumnTypeScanType)(nil)).Elem(),
		"RowsNextResultSet":	TypeOf((*pkg.RowsNextResultSet)(nil)).Elem(),
		"Stmt":	TypeOf((*pkg.Stmt)(nil)).Elem(),
		"StmtExecContext":	TypeOf((*pkg.StmtExecContext)(nil)).Elem(),
		"StmtQueryContext":	TypeOf((*pkg.StmtQueryContext)(nil)).Elem(),
		"Tx":	TypeOf((*pkg.Tx)(nil)).Elem(),
		"TxOptions":	TypeOf((*pkg.TxOptions)(nil)).Elem(),
		"Value":	TypeOf((*pkg.Value)(nil)).Elem(),
		"ValueConverter":	TypeOf((*pkg.ValueConverter)(nil)).Elem(),
		"Valuer":	TypeOf((*pkg.Valuer)(nil)).Elem(),
	}
}
