// this file was generated by gomacro command: import "debug/pe"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "debug/pe"
	. "reflect"
)

func Package_debug_pe() (map[string]Value, map[string]Type) {
	return map[string]Value{
			"COFFSymbolSize":               ValueOf(pkg.COFFSymbolSize),
			"IMAGE_FILE_MACHINE_AM33":      ValueOf(pkg.IMAGE_FILE_MACHINE_AM33),
			"IMAGE_FILE_MACHINE_AMD64":     ValueOf(pkg.IMAGE_FILE_MACHINE_AMD64),
			"IMAGE_FILE_MACHINE_ARM":       ValueOf(pkg.IMAGE_FILE_MACHINE_ARM),
			"IMAGE_FILE_MACHINE_EBC":       ValueOf(pkg.IMAGE_FILE_MACHINE_EBC),
			"IMAGE_FILE_MACHINE_I386":      ValueOf(pkg.IMAGE_FILE_MACHINE_I386),
			"IMAGE_FILE_MACHINE_IA64":      ValueOf(pkg.IMAGE_FILE_MACHINE_IA64),
			"IMAGE_FILE_MACHINE_M32R":      ValueOf(pkg.IMAGE_FILE_MACHINE_M32R),
			"IMAGE_FILE_MACHINE_MIPS16":    ValueOf(pkg.IMAGE_FILE_MACHINE_MIPS16),
			"IMAGE_FILE_MACHINE_MIPSFPU":   ValueOf(pkg.IMAGE_FILE_MACHINE_MIPSFPU),
			"IMAGE_FILE_MACHINE_MIPSFPU16": ValueOf(pkg.IMAGE_FILE_MACHINE_MIPSFPU16),
			"IMAGE_FILE_MACHINE_POWERPC":   ValueOf(pkg.IMAGE_FILE_MACHINE_POWERPC),
			"IMAGE_FILE_MACHINE_POWERPCFP": ValueOf(pkg.IMAGE_FILE_MACHINE_POWERPCFP),
			"IMAGE_FILE_MACHINE_R4000":     ValueOf(pkg.IMAGE_FILE_MACHINE_R4000),
			"IMAGE_FILE_MACHINE_SH3":       ValueOf(pkg.IMAGE_FILE_MACHINE_SH3),
			"IMAGE_FILE_MACHINE_SH3DSP":    ValueOf(pkg.IMAGE_FILE_MACHINE_SH3DSP),
			"IMAGE_FILE_MACHINE_SH4":       ValueOf(pkg.IMAGE_FILE_MACHINE_SH4),
			"IMAGE_FILE_MACHINE_SH5":       ValueOf(pkg.IMAGE_FILE_MACHINE_SH5),
			"IMAGE_FILE_MACHINE_THUMB":     ValueOf(pkg.IMAGE_FILE_MACHINE_THUMB),
			"IMAGE_FILE_MACHINE_UNKNOWN":   ValueOf(pkg.IMAGE_FILE_MACHINE_UNKNOWN),
			"IMAGE_FILE_MACHINE_WCEMIPSV2": ValueOf(pkg.IMAGE_FILE_MACHINE_WCEMIPSV2),
			"NewFile":                      ValueOf(pkg.NewFile),
			"Open":                         ValueOf(pkg.Open),
		}, map[string]Type{
			"COFFSymbol":       TypeOf((*pkg.COFFSymbol)(nil)).Elem(),
			"DataDirectory":    TypeOf((*pkg.DataDirectory)(nil)).Elem(),
			"File":             TypeOf((*pkg.File)(nil)).Elem(),
			"FileHeader":       TypeOf((*pkg.FileHeader)(nil)).Elem(),
			"FormatError":      TypeOf((*pkg.FormatError)(nil)).Elem(),
			"ImportDirectory":  TypeOf((*pkg.ImportDirectory)(nil)).Elem(),
			"OptionalHeader32": TypeOf((*pkg.OptionalHeader32)(nil)).Elem(),
			"OptionalHeader64": TypeOf((*pkg.OptionalHeader64)(nil)).Elem(),
			"Reloc":            TypeOf((*pkg.Reloc)(nil)).Elem(),
			"Section":          TypeOf((*pkg.Section)(nil)).Elem(),
			"SectionHeader":    TypeOf((*pkg.SectionHeader)(nil)).Elem(),
			"SectionHeader32":  TypeOf((*pkg.SectionHeader32)(nil)).Elem(),
			"StringTable":      TypeOf((*pkg.StringTable)(nil)).Elem(),
			"Symbol":           TypeOf((*pkg.Symbol)(nil)).Elem(),
		}
}

func init() {
	binds, types := Package_debug_pe()
	Binds["debug/pe"] = binds
	Types["debug/pe"] = types
}
