// this file was generated by gomacro command: import "debug/plan9obj"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	"debug/plan9obj"
)

func init() {
	Binds["debug/plan9obj"] = map[string]Value{
		"Magic386":	ValueOf(plan9obj.Magic386),
		"Magic64":	ValueOf(plan9obj.Magic64),
		"MagicAMD64":	ValueOf(plan9obj.MagicAMD64),
		"MagicARM":	ValueOf(plan9obj.MagicARM),
		"NewFile":	ValueOf(plan9obj.NewFile),
		"Open":	ValueOf(plan9obj.Open),
	}
	Types["debug/plan9obj"] = map[string]Type{
		"File":	TypeOf((*plan9obj.File)(nil)).Elem(),
		"FileHeader":	TypeOf((*plan9obj.FileHeader)(nil)).Elem(),
		"Section":	TypeOf((*plan9obj.Section)(nil)).Elem(),
		"SectionHeader":	TypeOf((*plan9obj.SectionHeader)(nil)).Elem(),
		"Sym":	TypeOf((*plan9obj.Sym)(nil)).Elem(),
	}
	Proxies["debug/plan9obj"] = map[string]Type{
	}
}
