// this file was generated by gomacro command: import _b "embed"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	embed "embed"
)

// reflection: allow interpreted code to import "embed"
func init() {
	Packages["embed"] = Package{
		Name: "embed",
		Types: map[string]Type{
			"FS":	TypeOf((*embed.FS)(nil)).Elem(),
		}, 
	}
}
