// this file was generated by gomacro command: import "encoding/pem"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	"encoding/pem"
)

func init() {
	Binds["encoding/pem"] = map[string]Value{
		"Decode":	ValueOf(pem.Decode),
		"Encode":	ValueOf(pem.Encode),
		"EncodeToMemory":	ValueOf(pem.EncodeToMemory),
	}
	Types["encoding/pem"] = map[string]Type{
		"Block":	TypeOf((*pem.Block)(nil)).Elem(),
	}
	Proxies["encoding/pem"] = map[string]Type{
	}
}
