// this file was generated by gomacro command: import "encoding/hex"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	"encoding/hex"
)

func init() {
	Binds["encoding/hex"] = map[string]Value{
		"Decode":	ValueOf(hex.Decode),
		"DecodeString":	ValueOf(hex.DecodeString),
		"DecodedLen":	ValueOf(hex.DecodedLen),
		"Dump":	ValueOf(hex.Dump),
		"Dumper":	ValueOf(hex.Dumper),
		"Encode":	ValueOf(hex.Encode),
		"EncodeToString":	ValueOf(hex.EncodeToString),
		"EncodedLen":	ValueOf(hex.EncodedLen),
		"ErrLength":	ValueOf(&hex.ErrLength).Elem(),
	}
	Types["encoding/hex"] = map[string]Type{
		"InvalidByteError":	TypeOf((*hex.InvalidByteError)(nil)).Elem(),
	}
	Proxies["encoding/hex"] = map[string]Type{
	}
}
