// this file was generated by gomacro command: import "encoding/csv"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	"encoding/csv"
)

func init() {
	Binds["encoding/csv"] = map[string]Value{
		"ErrBareQuote":	ValueOf(&csv.ErrBareQuote).Elem(),
		"ErrFieldCount":	ValueOf(&csv.ErrFieldCount).Elem(),
		"ErrQuote":	ValueOf(&csv.ErrQuote).Elem(),
		"ErrTrailingComma":	ValueOf(&csv.ErrTrailingComma).Elem(),
		"NewReader":	ValueOf(csv.NewReader),
		"NewWriter":	ValueOf(csv.NewWriter),
	}
	Types["encoding/csv"] = map[string]Type{
		"ParseError":	TypeOf((*csv.ParseError)(nil)).Elem(),
		"Reader":	TypeOf((*csv.Reader)(nil)).Elem(),
		"Writer":	TypeOf((*csv.Writer)(nil)).Elem(),
	}
	Proxies["encoding/csv"] = map[string]Type{
	}
}
