// this file was generated by gomacro command: import _b "encoding/asn1"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	"encoding/asn1"
)

// reflection: allow interpreted code to import "encoding/asn1"
func init() {
	Packages["encoding/asn1"] = Package{
	Binds: map[string]Value{
		"ClassApplication":	ValueOf(asn1.ClassApplication),
		"ClassContextSpecific":	ValueOf(asn1.ClassContextSpecific),
		"ClassPrivate":	ValueOf(asn1.ClassPrivate),
		"ClassUniversal":	ValueOf(asn1.ClassUniversal),
		"Marshal":	ValueOf(asn1.Marshal),
		"TagBitString":	ValueOf(asn1.TagBitString),
		"TagBoolean":	ValueOf(asn1.TagBoolean),
		"TagEnum":	ValueOf(asn1.TagEnum),
		"TagGeneralString":	ValueOf(asn1.TagGeneralString),
		"TagGeneralizedTime":	ValueOf(asn1.TagGeneralizedTime),
		"TagIA5String":	ValueOf(asn1.TagIA5String),
		"TagInteger":	ValueOf(asn1.TagInteger),
		"TagOID":	ValueOf(asn1.TagOID),
		"TagOctetString":	ValueOf(asn1.TagOctetString),
		"TagPrintableString":	ValueOf(asn1.TagPrintableString),
		"TagSequence":	ValueOf(asn1.TagSequence),
		"TagSet":	ValueOf(asn1.TagSet),
		"TagT61String":	ValueOf(asn1.TagT61String),
		"TagUTCTime":	ValueOf(asn1.TagUTCTime),
		"TagUTF8String":	ValueOf(asn1.TagUTF8String),
		"Unmarshal":	ValueOf(asn1.Unmarshal),
		"UnmarshalWithParams":	ValueOf(asn1.UnmarshalWithParams),
	},
	Types: map[string]Type{
		"BitString":	TypeOf((*asn1.BitString)(nil)).Elem(),
		"Enumerated":	TypeOf((*asn1.Enumerated)(nil)).Elem(),
		"Flag":	TypeOf((*asn1.Flag)(nil)).Elem(),
		"ObjectIdentifier":	TypeOf((*asn1.ObjectIdentifier)(nil)).Elem(),
		"RawContent":	TypeOf((*asn1.RawContent)(nil)).Elem(),
		"RawValue":	TypeOf((*asn1.RawValue)(nil)).Elem(),
		"StructuralError":	TypeOf((*asn1.StructuralError)(nil)).Elem(),
		"SyntaxError":	TypeOf((*asn1.SyntaxError)(nil)).Elem(),
	},
	Proxies: map[string]Type{
	},
	Wrappers: map[string][]string{
	} }
}
