// this file was generated by gomacro command: import "encoding/base64"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "encoding/base64"
	. "reflect"
)

func init() {
	Binds["encoding/base64"] = map[string]Value{
		"NewDecoder":	ValueOf(pkg.NewDecoder),
		"NewEncoder":	ValueOf(pkg.NewEncoder),
		"NewEncoding":	ValueOf(pkg.NewEncoding),
		"NoPadding":	ValueOf(pkg.NoPadding),
		"RawStdEncoding":	ValueOf(&pkg.RawStdEncoding).Elem(),
		"RawURLEncoding":	ValueOf(&pkg.RawURLEncoding).Elem(),
		"StdEncoding":	ValueOf(&pkg.StdEncoding).Elem(),
		"StdPadding":	ValueOf(pkg.StdPadding),
		"URLEncoding":	ValueOf(&pkg.URLEncoding).Elem(),
	}
	Types["encoding/base64"] = map[string]Type{
		"CorruptInputError":	TypeOf((*pkg.CorruptInputError)(nil)).Elem(),
		"Encoding":	TypeOf((*pkg.Encoding)(nil)).Elem(),
	}
}
