// this file was generated by gomacro command: import "encoding/ascii85"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "encoding/ascii85"
	. "reflect"
)

func Package_encoding_ascii85() (map[string]Value, map[string]Type) {
	return map[string]Value{
			"Decode":        ValueOf(pkg.Decode),
			"Encode":        ValueOf(pkg.Encode),
			"MaxEncodedLen": ValueOf(pkg.MaxEncodedLen),
			"NewDecoder":    ValueOf(pkg.NewDecoder),
			"NewEncoder":    ValueOf(pkg.NewEncoder),
		}, map[string]Type{
			"CorruptInputError": TypeOf((*pkg.CorruptInputError)(nil)).Elem(),
		}
}

func init() {
	binds, types := Package_encoding_ascii85()
	Binds["encoding/ascii85"] = binds
	Types["encoding/ascii85"] = types
}
