// this file was generated by gomacro command: import "encoding/base32"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "encoding/base32"
	. "reflect"
)

func init() {
	Binds["encoding/base32"] = map[string]Value{
		"HexEncoding":	ValueOf(&pkg.HexEncoding).Elem(),
		"NewDecoder":	ValueOf(pkg.NewDecoder),
		"NewEncoder":	ValueOf(pkg.NewEncoder),
		"NewEncoding":	ValueOf(pkg.NewEncoding),
		"StdEncoding":	ValueOf(&pkg.StdEncoding).Elem(),
	}
	Types["encoding/base32"] = map[string]Type{
		"CorruptInputError":	TypeOf((*pkg.CorruptInputError)(nil)).Elem(),
		"Encoding":	TypeOf((*pkg.Encoding)(nil)).Elem(),
	}
}
