// this file was generated by gomacro command: import "errors"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	"errors"
)

func init() {
	Packages["errors"] = Package{
	Binds: map[string]Value{
		"New":	ValueOf(errors.New),
	},
	Types: map[string]Type{
	},
	Proxies: map[string]Type{
	} }
}
