// this file was generated by gomacro command: import _b "errors"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	errors "errors"
)

// reflection: allow interpreted code to import "errors"
func init() {
	Packages["errors"] = Package{
	Name: "errors",
	Binds: map[string]Value{
		"As":	ValueOf(errors.As),
		"Is":	ValueOf(errors.Is),
		"New":	ValueOf(errors.New),
		"Unwrap":	ValueOf(errors.Unwrap),
	}, 
	}
}
