// this file was generated by gomacro command: import "errors"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	"errors"
)

func init() {
	Binds["errors"] = map[string]Value{
		"New":	ValueOf(errors.New),
	}
	Types["errors"] = map[string]Type{
	}
	Proxies["errors"] = map[string]Type{
	}
}
