// this file was generated by gomacro command: import "fmt"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "fmt"
	. "reflect"
)

func init() {
	Binds["fmt"] = map[string]Value{
		"Errorf":	ValueOf(pkg.Errorf),
		"Fprint":	ValueOf(pkg.Fprint),
		"Fprintf":	ValueOf(pkg.Fprintf),
		"Fprintln":	ValueOf(pkg.Fprintln),
		"Fscan":	ValueOf(pkg.Fscan),
		"Fscanf":	ValueOf(pkg.Fscanf),
		"Fscanln":	ValueOf(pkg.Fscanln),
		"Print":	ValueOf(pkg.Print),
		"Printf":	ValueOf(pkg.Printf),
		"Println":	ValueOf(pkg.Println),
		"Scan":	ValueOf(pkg.Scan),
		"Scanf":	ValueOf(pkg.Scanf),
		"Scanln":	ValueOf(pkg.Scanln),
		"Sprint":	ValueOf(pkg.Sprint),
		"Sprintf":	ValueOf(pkg.Sprintf),
		"Sprintln":	ValueOf(pkg.Sprintln),
		"Sscan":	ValueOf(pkg.Sscan),
		"Sscanf":	ValueOf(pkg.Sscanf),
		"Sscanln":	ValueOf(pkg.Sscanln),
	}
	Types["fmt"] = map[string]Type{
		"Formatter":	TypeOf((*pkg.Formatter)(nil)).Elem(),
		"GoStringer":	TypeOf((*pkg.GoStringer)(nil)).Elem(),
		"ScanState":	TypeOf((*pkg.ScanState)(nil)).Elem(),
		"Scanner":	TypeOf((*pkg.Scanner)(nil)).Elem(),
		"State":	TypeOf((*pkg.State)(nil)).Elem(),
		"Stringer":	TypeOf((*pkg.Stringer)(nil)).Elem(),
	}
}
