// this file was generated by gomacro command: import "go/constant"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	"go/constant"
)

func init() {
	Packages["go/constant"] = Package{
	Binds: map[string]Value{
		"BinaryOp":	ValueOf(constant.BinaryOp),
		"BitLen":	ValueOf(constant.BitLen),
		"Bool":	ValueOf(constant.Bool),
		"BoolVal":	ValueOf(constant.BoolVal),
		"Bytes":	ValueOf(constant.Bytes),
		"Compare":	ValueOf(constant.Compare),
		"Complex":	ValueOf(constant.Complex),
		"Denom":	ValueOf(constant.Denom),
		"Float":	ValueOf(constant.Float),
		"Float32Val":	ValueOf(constant.Float32Val),
		"Float64Val":	ValueOf(constant.Float64Val),
		"Imag":	ValueOf(constant.Imag),
		"Int":	ValueOf(constant.Int),
		"Int64Val":	ValueOf(constant.Int64Val),
		"MakeBool":	ValueOf(constant.MakeBool),
		"MakeFloat64":	ValueOf(constant.MakeFloat64),
		"MakeFromBytes":	ValueOf(constant.MakeFromBytes),
		"MakeFromLiteral":	ValueOf(constant.MakeFromLiteral),
		"MakeImag":	ValueOf(constant.MakeImag),
		"MakeInt64":	ValueOf(constant.MakeInt64),
		"MakeString":	ValueOf(constant.MakeString),
		"MakeUint64":	ValueOf(constant.MakeUint64),
		"MakeUnknown":	ValueOf(constant.MakeUnknown),
		"Num":	ValueOf(constant.Num),
		"Real":	ValueOf(constant.Real),
		"Shift":	ValueOf(constant.Shift),
		"Sign":	ValueOf(constant.Sign),
		"String":	ValueOf(constant.String),
		"StringVal":	ValueOf(constant.StringVal),
		"ToComplex":	ValueOf(constant.ToComplex),
		"ToFloat":	ValueOf(constant.ToFloat),
		"ToInt":	ValueOf(constant.ToInt),
		"Uint64Val":	ValueOf(constant.Uint64Val),
		"UnaryOp":	ValueOf(constant.UnaryOp),
		"Unknown":	ValueOf(constant.Unknown),
	},
	Types: map[string]Type{
		"Kind":	TypeOf((*constant.Kind)(nil)).Elem(),
		"Value":	TypeOf((*constant.Value)(nil)).Elem(),
	},
	Proxies: map[string]Type{
		"Value":	TypeOf((*Value_go_constant)(nil)).Elem(),
	} }
}

// --------------- proxy for go/constant.Value ---------------
type Value_go_constant struct {
	Object	interface{}
	ExactString_	func() string
	Kind_	func() constant.Kind
	String_	func() string
}
func (Proxy Value_go_constant) ExactString() string {
	return Proxy.ExactString_()
}
func (Proxy Value_go_constant) Kind() constant.Kind {
	return Proxy.Kind_()
}
func (Proxy Value_go_constant) String() string {
	return Proxy.String_()
}
