// this file was generated by gomacro command: import "go/format"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	"go/format"
)

func init() {
	Packages["go/format"] = Package{
	Binds: map[string]Value{
		"Node":	ValueOf(format.Node),
		"Source":	ValueOf(format.Source),
	},
	Types: map[string]Type{
	},
	Proxies: map[string]Type{
	} }
}
