// this file was generated by gomacro command: import _b "go/format"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	"go/format"
	. "reflect"
)

// reflection: allow interpreted code to import "go/format"
func init() {
	Packages["go/format"] = Package{
		Binds: map[string]Value{
			"Node":   ValueOf(format.Node),
			"Source": ValueOf(format.Source),
		},
	}
}
