// this file was generated by gomacro command: import "go/format"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "go/format"
	. "reflect"
)

func Package_go_format() (map[string]Value, map[string]Type) {
	return map[string]Value{
			"Node":   ValueOf(pkg.Node),
			"Source": ValueOf(pkg.Source),
		}, map[string]Type{}
}

func init() {
	binds, types := Package_go_format()
	Binds["go/format"] = binds
	Types["go/format"] = types
}
