// this file was generated by gomacro command: import "go/importer"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "go/importer"
	. "reflect"
)

func init() {
	Binds["go/importer"] = map[string]Value{
		"Default":	ValueOf(pkg.Default),
		"For":	ValueOf(pkg.For),
	}
	Types["go/importer"] = map[string]Type{
		"Lookup":	TypeOf((*pkg.Lookup)(nil)).Elem(),
	}
}
