// this file was generated by gomacro command: import "go/importer"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "go/importer"
	. "reflect"
)

func Package_go_importer() (map[string]Value, map[string]Type) {
	return map[string]Value{
			"Default": ValueOf(pkg.Default),
			"For":     ValueOf(pkg.For),
		}, map[string]Type{
			"Lookup": TypeOf((*pkg.Lookup)(nil)).Elem(),
		}
}

func init() {
	binds, types := Package_go_importer()
	Binds["go/importer"] = binds
	Types["go/importer"] = types
}
