// this file was generated by gomacro command: import "go/printer"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	"go/printer"
)

func init() {
	Binds["go/printer"] = map[string]Value{
		"Fprint":	ValueOf(printer.Fprint),
		"RawFormat":	ValueOf(printer.RawFormat),
		"SourcePos":	ValueOf(printer.SourcePos),
		"TabIndent":	ValueOf(printer.TabIndent),
		"UseSpaces":	ValueOf(printer.UseSpaces),
	}
	Types["go/printer"] = map[string]Type{
		"CommentedNode":	TypeOf((*printer.CommentedNode)(nil)).Elem(),
		"Config":	TypeOf((*printer.Config)(nil)).Elem(),
		"Mode":	TypeOf((*printer.Mode)(nil)).Elem(),
	}
	Proxies["go/printer"] = map[string]Type{
	}
}
