// this file was generated by gomacro command: import "go/scanner"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "go/scanner"
	. "reflect"
)

func init() {
	Binds["go/scanner"] = map[string]Value{
		"PrintError":	ValueOf(pkg.PrintError),
		"ScanComments":	ValueOf(pkg.ScanComments),
	}
	Types["go/scanner"] = map[string]Type{
		"Error":	TypeOf((*pkg.Error)(nil)).Elem(),
		"ErrorHandler":	TypeOf((*pkg.ErrorHandler)(nil)).Elem(),
		"ErrorList":	TypeOf((*pkg.ErrorList)(nil)).Elem(),
		"Mode":	TypeOf((*pkg.Mode)(nil)).Elem(),
		"Scanner":	TypeOf((*pkg.Scanner)(nil)).Elem(),
	}
}
