// this file was generated by gomacro command: import "hash/crc32"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	"hash/crc32"
)

func init() {
	Binds["hash/crc32"] = map[string]Value{
		"Castagnoli":	ValueOf(crc32.Castagnoli),
		"Checksum":	ValueOf(crc32.Checksum),
		"ChecksumIEEE":	ValueOf(crc32.ChecksumIEEE),
		"IEEE":	ValueOf(crc32.IEEE),
		"IEEETable":	ValueOf(&crc32.IEEETable).Elem(),
		"Koopman":	ValueOf(crc32.Koopman),
		"MakeTable":	ValueOf(crc32.MakeTable),
		"New":	ValueOf(crc32.New),
		"NewIEEE":	ValueOf(crc32.NewIEEE),
		"Size":	ValueOf(crc32.Size),
		"Update":	ValueOf(crc32.Update),
	}
	Types["hash/crc32"] = map[string]Type{
		"Table":	TypeOf((*crc32.Table)(nil)).Elem(),
	}
	Proxies["hash/crc32"] = map[string]Type{
	}
}
