// this file was generated by gomacro command: import _b "hash/maphash"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	maphash "hash/maphash"
)

// reflection: allow interpreted code to import "hash/maphash"
func init() {
	Packages["hash/maphash"] = Package{
		Name: "maphash",
		Binds: map[string]Value{
			"MakeSeed":	ValueOf(maphash.MakeSeed),
		}, Types: map[string]Type{
			"Hash":	TypeOf((*maphash.Hash)(nil)).Elem(),
			"Seed":	TypeOf((*maphash.Seed)(nil)).Elem(),
		}, 
	}
}
