// this file was generated by gomacro command: import "hash/fnv"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	"hash/fnv"
)

func init() {
	Packages["hash/fnv"] = Package{
	Binds: map[string]Value{
		"New32":	ValueOf(fnv.New32),
		"New32a":	ValueOf(fnv.New32a),
		"New64":	ValueOf(fnv.New64),
		"New64a":	ValueOf(fnv.New64a),
	},
	Types: map[string]Type{
	},
	Proxies: map[string]Type{
	} }
}
