// this file was generated by gomacro command: import "hash/crc64"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "hash/crc64"
	. "reflect"
)

func Package_hash_crc64() (map[string]Value, map[string]Type) {
	return map[string]Value{
			"Checksum":  ValueOf(pkg.Checksum),
			"ECMA":      ValueOf(uint64(pkg.ECMA)),
			"ISO":       ValueOf(uint64(pkg.ISO)),
			"MakeTable": ValueOf(pkg.MakeTable),
			"New":       ValueOf(pkg.New),
			"Size":      ValueOf(pkg.Size),
			"Update":    ValueOf(pkg.Update),
		}, map[string]Type{
			"Table": TypeOf((*pkg.Table)(nil)).Elem(),
		}
}

func init() {
	binds, types := Package_hash_crc64()
	Binds["hash/crc64"] = binds
	Types["hash/crc64"] = types
}
