// this file was generated by gomacro command: import "hash/crc32"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "hash/crc32"
	. "reflect"
)

func init() {
	Binds["hash/crc32"] = map[string]Value{
		"Castagnoli":	ValueOf(pkg.Castagnoli),
		"Checksum":	ValueOf(pkg.Checksum),
		"ChecksumIEEE":	ValueOf(pkg.ChecksumIEEE),
		"IEEE":	ValueOf(pkg.IEEE),
		"IEEETable":	ValueOf(&pkg.IEEETable).Elem(),
		"Koopman":	ValueOf(pkg.Koopman),
		"MakeTable":	ValueOf(pkg.MakeTable),
		"New":	ValueOf(pkg.New),
		"NewIEEE":	ValueOf(pkg.NewIEEE),
		"Size":	ValueOf(pkg.Size),
		"Update":	ValueOf(pkg.Update),
	}
	Types["hash/crc32"] = map[string]Type{
		"Table":	TypeOf((*pkg.Table)(nil)).Elem(),
	}
}
