// this file was generated by gomacro command: import "html"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "html"
	. "reflect"
)

func init() {
	Binds["html"] = map[string]Value{
		"EscapeString":	ValueOf(pkg.EscapeString),
		"UnescapeString":	ValueOf(pkg.UnescapeString),
	}
	Types["html"] = map[string]Type{
	}
}
