// this file was generated by gomacro command: import "image/png"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	"image/png"
)

func init() {
	Binds["image/png"] = map[string]Value{
		"BestCompression":	ValueOf(png.BestCompression),
		"BestSpeed":	ValueOf(png.BestSpeed),
		"Decode":	ValueOf(png.Decode),
		"DecodeConfig":	ValueOf(png.DecodeConfig),
		"DefaultCompression":	ValueOf(png.DefaultCompression),
		"Encode":	ValueOf(png.Encode),
		"NoCompression":	ValueOf(png.NoCompression),
	}
	Types["image/png"] = map[string]Type{
		"CompressionLevel":	TypeOf((*png.CompressionLevel)(nil)).Elem(),
		"Encoder":	TypeOf((*png.Encoder)(nil)).Elem(),
		"FormatError":	TypeOf((*png.FormatError)(nil)).Elem(),
		"UnsupportedError":	TypeOf((*png.UnsupportedError)(nil)).Elem(),
	}
	Proxies["image/png"] = map[string]Type{
	}
}
