// this file was generated by gomacro command: import "image/color/palette"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "image/color/palette"
	. "reflect"
)

func init() {
	Binds["image/color/palette"] = map[string]Value{
		"Plan9":	ValueOf(&pkg.Plan9).Elem(),
		"WebSafe":	ValueOf(&pkg.WebSafe).Elem(),
	}
	Types["image/color/palette"] = map[string]Type{
	}
}
