// this file was generated by gomacro command: import "image/color/palette"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "image/color/palette"
	. "reflect"
)

func Package_image_color_palette() (map[string]Value, map[string]Type) {
	return map[string]Value{
			"Plan9":   ValueOf(&pkg.Plan9).Elem(),
			"WebSafe": ValueOf(&pkg.WebSafe).Elem(),
		}, map[string]Type{}
}

func init() {
	binds, types := Package_image_color_palette()
	Binds["image/color/palette"] = binds
	Types["image/color/palette"] = types
}
