// this file was generated by gomacro command: import "image/png"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "image/png"
	. "reflect"
)

func init() {
	Binds["image/png"] = map[string]Value{
		"BestCompression":	ValueOf(pkg.BestCompression),
		"BestSpeed":	ValueOf(pkg.BestSpeed),
		"Decode":	ValueOf(pkg.Decode),
		"DecodeConfig":	ValueOf(pkg.DecodeConfig),
		"DefaultCompression":	ValueOf(pkg.DefaultCompression),
		"Encode":	ValueOf(pkg.Encode),
		"NoCompression":	ValueOf(pkg.NoCompression),
	}
	Types["image/png"] = map[string]Type{
		"CompressionLevel":	TypeOf((*pkg.CompressionLevel)(nil)).Elem(),
		"Encoder":	TypeOf((*pkg.Encoder)(nil)).Elem(),
		"FormatError":	TypeOf((*pkg.FormatError)(nil)).Elem(),
		"UnsupportedError":	TypeOf((*pkg.UnsupportedError)(nil)).Elem(),
	}
}
