// this file was generated by gomacro command: import "image/gif"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	"image/gif"
)

func init() {
	Binds["image/gif"] = map[string]Value{
		"Decode":	ValueOf(gif.Decode),
		"DecodeAll":	ValueOf(gif.DecodeAll),
		"DecodeConfig":	ValueOf(gif.DecodeConfig),
		"DisposalBackground":	ValueOf(gif.DisposalBackground),
		"DisposalNone":	ValueOf(gif.DisposalNone),
		"DisposalPrevious":	ValueOf(gif.DisposalPrevious),
		"Encode":	ValueOf(gif.Encode),
		"EncodeAll":	ValueOf(gif.EncodeAll),
	}
	Types["image/gif"] = map[string]Type{
		"GIF":	TypeOf((*gif.GIF)(nil)).Elem(),
		"Options":	TypeOf((*gif.Options)(nil)).Elem(),
	}
	Proxies["image/gif"] = map[string]Type{
	}
}
