// this file was generated by gomacro command: import "image"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "image"
	. "reflect"
)

func init() {
	Binds["image"] = map[string]Value{
		"Black":	ValueOf(&pkg.Black).Elem(),
		"Decode":	ValueOf(pkg.Decode),
		"DecodeConfig":	ValueOf(pkg.DecodeConfig),
		"ErrFormat":	ValueOf(&pkg.ErrFormat).Elem(),
		"NewAlpha":	ValueOf(pkg.NewAlpha),
		"NewAlpha16":	ValueOf(pkg.NewAlpha16),
		"NewCMYK":	ValueOf(pkg.NewCMYK),
		"NewGray":	ValueOf(pkg.NewGray),
		"NewGray16":	ValueOf(pkg.NewGray16),
		"NewNRGBA":	ValueOf(pkg.NewNRGBA),
		"NewNRGBA64":	ValueOf(pkg.NewNRGBA64),
		"NewNYCbCrA":	ValueOf(pkg.NewNYCbCrA),
		"NewPaletted":	ValueOf(pkg.NewPaletted),
		"NewRGBA":	ValueOf(pkg.NewRGBA),
		"NewRGBA64":	ValueOf(pkg.NewRGBA64),
		"NewUniform":	ValueOf(pkg.NewUniform),
		"NewYCbCr":	ValueOf(pkg.NewYCbCr),
		"Opaque":	ValueOf(&pkg.Opaque).Elem(),
		"Pt":	ValueOf(pkg.Pt),
		"Rect":	ValueOf(pkg.Rect),
		"RegisterFormat":	ValueOf(pkg.RegisterFormat),
		"Transparent":	ValueOf(&pkg.Transparent).Elem(),
		"White":	ValueOf(&pkg.White).Elem(),
		"YCbCrSubsampleRatio410":	ValueOf(pkg.YCbCrSubsampleRatio410),
		"YCbCrSubsampleRatio411":	ValueOf(pkg.YCbCrSubsampleRatio411),
		"YCbCrSubsampleRatio420":	ValueOf(pkg.YCbCrSubsampleRatio420),
		"YCbCrSubsampleRatio422":	ValueOf(pkg.YCbCrSubsampleRatio422),
		"YCbCrSubsampleRatio440":	ValueOf(pkg.YCbCrSubsampleRatio440),
		"YCbCrSubsampleRatio444":	ValueOf(pkg.YCbCrSubsampleRatio444),
		"ZP":	ValueOf(&pkg.ZP).Elem(),
		"ZR":	ValueOf(&pkg.ZR).Elem(),
	}
	Types["image"] = map[string]Type{
		"Alpha":	TypeOf((*pkg.Alpha)(nil)).Elem(),
		"Alpha16":	TypeOf((*pkg.Alpha16)(nil)).Elem(),
		"CMYK":	TypeOf((*pkg.CMYK)(nil)).Elem(),
		"Config":	TypeOf((*pkg.Config)(nil)).Elem(),
		"Gray":	TypeOf((*pkg.Gray)(nil)).Elem(),
		"Gray16":	TypeOf((*pkg.Gray16)(nil)).Elem(),
		"Image":	TypeOf((*pkg.Image)(nil)).Elem(),
		"NRGBA":	TypeOf((*pkg.NRGBA)(nil)).Elem(),
		"NRGBA64":	TypeOf((*pkg.NRGBA64)(nil)).Elem(),
		"NYCbCrA":	TypeOf((*pkg.NYCbCrA)(nil)).Elem(),
		"Paletted":	TypeOf((*pkg.Paletted)(nil)).Elem(),
		"PalettedImage":	TypeOf((*pkg.PalettedImage)(nil)).Elem(),
		"Point":	TypeOf((*pkg.Point)(nil)).Elem(),
		"RGBA":	TypeOf((*pkg.RGBA)(nil)).Elem(),
		"RGBA64":	TypeOf((*pkg.RGBA64)(nil)).Elem(),
		"Rectangle":	TypeOf((*pkg.Rectangle)(nil)).Elem(),
		"Uniform":	TypeOf((*pkg.Uniform)(nil)).Elem(),
		"YCbCr":	TypeOf((*pkg.YCbCr)(nil)).Elem(),
		"YCbCrSubsampleRatio":	TypeOf((*pkg.YCbCrSubsampleRatio)(nil)).Elem(),
	}
}
