// this file was generated by gomacro command: import "image/draw"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "image/draw"
	. "reflect"
)

func init() {
	Binds["image/draw"] = map[string]Value{
		"Draw":	ValueOf(pkg.Draw),
		"DrawMask":	ValueOf(pkg.DrawMask),
		"FloydSteinberg":	ValueOf(&pkg.FloydSteinberg).Elem(),
		"Over":	ValueOf(pkg.Over),
		"Src":	ValueOf(pkg.Src),
	}
	Types["image/draw"] = map[string]Type{
		"Drawer":	TypeOf((*pkg.Drawer)(nil)).Elem(),
		"Image":	TypeOf((*pkg.Image)(nil)).Elem(),
		"Op":	TypeOf((*pkg.Op)(nil)).Elem(),
		"Quantizer":	TypeOf((*pkg.Quantizer)(nil)).Elem(),
	}
}
