// this file was generated by gomacro command: import "index/suffixarray"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "index/suffixarray"
	. "reflect"
)

func init() {
	Binds["index/suffixarray"] = map[string]Value{
		"New":	ValueOf(pkg.New),
	}
	Types["index/suffixarray"] = map[string]Type{
		"Index":	TypeOf((*pkg.Index)(nil)).Elem(),
	}
}
