// this file was generated by gomacro command: import "index/suffixarray"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	"index/suffixarray"
)

func init() {
	Binds["index/suffixarray"] = map[string]Value{
		"New":	ValueOf(suffixarray.New),
	}
	Types["index/suffixarray"] = map[string]Type{
		"Index":	TypeOf((*suffixarray.Index)(nil)).Elem(),
	}
	Proxies["index/suffixarray"] = map[string]Type{
	}
}
