// this file was generated by gomacro command: import _b "index/suffixarray"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	"index/suffixarray"
	. "reflect"
)

// reflection: allow interpreted code to import "index/suffixarray"
func init() {
	Packages["index/suffixarray"] = Package{
		Binds: map[string]Value{
			"New": ValueOf(suffixarray.New),
		}, Types: map[string]Type{
			"Index": TypeOf((*suffixarray.Index)(nil)).Elem(),
		},
	}
}
