// this file was generated by gomacro command: import "io/ioutil"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "io/ioutil"
	. "reflect"
)

func init() {
	Binds["io/ioutil"] = map[string]Value{
		"Discard":	ValueOf(&pkg.Discard).Elem(),
		"NopCloser":	ValueOf(pkg.NopCloser),
		"ReadAll":	ValueOf(pkg.ReadAll),
		"ReadDir":	ValueOf(pkg.ReadDir),
		"ReadFile":	ValueOf(pkg.ReadFile),
		"TempDir":	ValueOf(pkg.TempDir),
		"TempFile":	ValueOf(pkg.TempFile),
		"WriteFile":	ValueOf(pkg.WriteFile),
	}
	Types["io/ioutil"] = map[string]Type{
	}
}
