// this file was generated by gomacro command: import "log"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	"log"
)

func init() {
	Binds["log"] = map[string]Value{
		"Fatal":	ValueOf(log.Fatal),
		"Fatalf":	ValueOf(log.Fatalf),
		"Fatalln":	ValueOf(log.Fatalln),
		"Flags":	ValueOf(log.Flags),
		"LUTC":	ValueOf(log.LUTC),
		"Ldate":	ValueOf(log.Ldate),
		"Llongfile":	ValueOf(log.Llongfile),
		"Lmicroseconds":	ValueOf(log.Lmicroseconds),
		"Lshortfile":	ValueOf(log.Lshortfile),
		"LstdFlags":	ValueOf(log.LstdFlags),
		"Ltime":	ValueOf(log.Ltime),
		"New":	ValueOf(log.New),
		"Output":	ValueOf(log.Output),
		"Panic":	ValueOf(log.Panic),
		"Panicf":	ValueOf(log.Panicf),
		"Panicln":	ValueOf(log.Panicln),
		"Prefix":	ValueOf(log.Prefix),
		"Print":	ValueOf(log.Print),
		"Printf":	ValueOf(log.Printf),
		"Println":	ValueOf(log.Println),
		"SetFlags":	ValueOf(log.SetFlags),
		"SetOutput":	ValueOf(log.SetOutput),
		"SetPrefix":	ValueOf(log.SetPrefix),
	}
	Types["log"] = map[string]Type{
		"Logger":	TypeOf((*log.Logger)(nil)).Elem(),
	}
	Proxies["log"] = map[string]Type{
	}
}
