// this file was generated by gomacro command: import "mime"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "mime"
	. "reflect"
)

func init() {
	Binds["mime"] = map[string]Value{
		"AddExtensionType":	ValueOf(pkg.AddExtensionType),
		"BEncoding":	ValueOf(pkg.BEncoding),
		"ExtensionsByType":	ValueOf(pkg.ExtensionsByType),
		"FormatMediaType":	ValueOf(pkg.FormatMediaType),
		"ParseMediaType":	ValueOf(pkg.ParseMediaType),
		"QEncoding":	ValueOf(pkg.QEncoding),
		"TypeByExtension":	ValueOf(pkg.TypeByExtension),
	}
	Types["mime"] = map[string]Type{
		"WordDecoder":	TypeOf((*pkg.WordDecoder)(nil)).Elem(),
		"WordEncoder":	TypeOf((*pkg.WordEncoder)(nil)).Elem(),
	}
}
