// this file was generated by gomacro command: import "mime"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "mime"
	. "reflect"
)

func Package_mime() (map[string]Value, map[string]Type) {
	return map[string]Value{
			"AddExtensionType": ValueOf(pkg.AddExtensionType),
			"BEncoding":        ValueOf(pkg.BEncoding),
			"ExtensionsByType": ValueOf(pkg.ExtensionsByType),
			"FormatMediaType":  ValueOf(pkg.FormatMediaType),
			"ParseMediaType":   ValueOf(pkg.ParseMediaType),
			"QEncoding":        ValueOf(pkg.QEncoding),
			"TypeByExtension":  ValueOf(pkg.TypeByExtension),
		}, map[string]Type{
			"WordDecoder": TypeOf((*pkg.WordDecoder)(nil)).Elem(),
			"WordEncoder": TypeOf((*pkg.WordEncoder)(nil)).Elem(),
		}
}

func init() {
	binds, types := Package_mime()
	Binds["mime"] = binds
	Types["mime"] = types
}
