// this file was generated by gomacro command: import "net/http/httptest"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "net/http/httptest"
	. "reflect"
)

func init() {
	Binds["net/http/httptest"] = map[string]Value{
		"DefaultRemoteAddr":	ValueOf(pkg.DefaultRemoteAddr),
		"NewRecorder":	ValueOf(pkg.NewRecorder),
		"NewRequest":	ValueOf(pkg.NewRequest),
		"NewServer":	ValueOf(pkg.NewServer),
		"NewTLSServer":	ValueOf(pkg.NewTLSServer),
		"NewUnstartedServer":	ValueOf(pkg.NewUnstartedServer),
	}
	Types["net/http/httptest"] = map[string]Type{
		"ResponseRecorder":	TypeOf((*pkg.ResponseRecorder)(nil)).Elem(),
		"Server":	TypeOf((*pkg.Server)(nil)).Elem(),
	}
}
