// this file was generated by gomacro command: import "net/http/httptrace"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "net/http/httptrace"
	. "reflect"
)

func init() {
	Binds["net/http/httptrace"] = map[string]Value{
		"ContextClientTrace":	ValueOf(pkg.ContextClientTrace),
		"WithClientTrace":	ValueOf(pkg.WithClientTrace),
	}
	Types["net/http/httptrace"] = map[string]Type{
		"ClientTrace":	TypeOf((*pkg.ClientTrace)(nil)).Elem(),
		"DNSDoneInfo":	TypeOf((*pkg.DNSDoneInfo)(nil)).Elem(),
		"DNSStartInfo":	TypeOf((*pkg.DNSStartInfo)(nil)).Elem(),
		"GotConnInfo":	TypeOf((*pkg.GotConnInfo)(nil)).Elem(),
		"WroteRequestInfo":	TypeOf((*pkg.WroteRequestInfo)(nil)).Elem(),
	}
}
