// this file was generated by gomacro command: import "net/rpc/jsonrpc"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "net/rpc/jsonrpc"
	. "reflect"
)

func Package_net_rpc_jsonrpc() (map[string]Value, map[string]Type) {
	return map[string]Value{
			"Dial":           ValueOf(pkg.Dial),
			"NewClient":      ValueOf(pkg.NewClient),
			"NewClientCodec": ValueOf(pkg.NewClientCodec),
			"NewServerCodec": ValueOf(pkg.NewServerCodec),
			"ServeConn":      ValueOf(pkg.ServeConn),
		}, map[string]Type{}
}

func init() {
	binds, types := Package_net_rpc_jsonrpc()
	Binds["net/rpc/jsonrpc"] = binds
	Types["net/rpc/jsonrpc"] = types
}
