// this file was generated by gomacro command: import "net/http/pprof"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "net/http/pprof"
	. "reflect"
)

func init() {
	Binds["net/http/pprof"] = map[string]Value{
		"Cmdline":	ValueOf(pkg.Cmdline),
		"Handler":	ValueOf(pkg.Handler),
		"Index":	ValueOf(pkg.Index),
		"Profile":	ValueOf(pkg.Profile),
		"Symbol":	ValueOf(pkg.Symbol),
		"Trace":	ValueOf(pkg.Trace),
	}
	Types["net/http/pprof"] = map[string]Type{
	}
}
