// this file was generated by gomacro command: import "net/mail"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "net/mail"
	. "reflect"
)

func init() {
	Binds["net/mail"] = map[string]Value{
		"ErrHeaderNotPresent":	ValueOf(&pkg.ErrHeaderNotPresent).Elem(),
		"ParseAddress":	ValueOf(pkg.ParseAddress),
		"ParseAddressList":	ValueOf(pkg.ParseAddressList),
		"ParseDate":	ValueOf(pkg.ParseDate),
		"ReadMessage":	ValueOf(pkg.ReadMessage),
	}
	Types["net/mail"] = map[string]Type{
		"Address":	TypeOf((*pkg.Address)(nil)).Elem(),
		"AddressParser":	TypeOf((*pkg.AddressParser)(nil)).Elem(),
		"Header":	TypeOf((*pkg.Header)(nil)).Elem(),
		"Message":	TypeOf((*pkg.Message)(nil)).Elem(),
	}
}
