// this file was generated by gomacro command: import "net/http/cookiejar"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "net/http/cookiejar"
	. "reflect"
)

func init() {
	Binds["net/http/cookiejar"] = map[string]Value{
		"New":	ValueOf(pkg.New),
	}
	Types["net/http/cookiejar"] = map[string]Type{
		"Jar":	TypeOf((*pkg.Jar)(nil)).Elem(),
		"Options":	TypeOf((*pkg.Options)(nil)).Elem(),
		"PublicSuffixList":	TypeOf((*pkg.PublicSuffixList)(nil)).Elem(),
	}
}
