// this file was generated by gomacro command: import "net/http/fcgi"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "net/http/fcgi"
	. "reflect"
)

func Package_net_http_fcgi() (map[string]Value, map[string]Type) {
	return map[string]Value{
			"ErrConnClosed":     ValueOf(&pkg.ErrConnClosed).Elem(),
			"ErrRequestAborted": ValueOf(&pkg.ErrRequestAborted).Elem(),
			"Serve":             ValueOf(pkg.Serve),
		}, map[string]Type{}
}

func init() {
	binds, types := Package_net_http_fcgi()
	Binds["net/http/fcgi"] = binds
	Types["net/http/fcgi"] = types
}
