// this file was generated by gomacro command: import "net/url"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "net/url"
	. "reflect"
)

func init() {
	Binds["net/url"] = map[string]Value{
		"Parse":	ValueOf(pkg.Parse),
		"ParseQuery":	ValueOf(pkg.ParseQuery),
		"ParseRequestURI":	ValueOf(pkg.ParseRequestURI),
		"PathEscape":	ValueOf(pkg.PathEscape),
		"PathUnescape":	ValueOf(pkg.PathUnescape),
		"QueryEscape":	ValueOf(pkg.QueryEscape),
		"QueryUnescape":	ValueOf(pkg.QueryUnescape),
		"User":	ValueOf(pkg.User),
		"UserPassword":	ValueOf(pkg.UserPassword),
	}
	Types["net/url"] = map[string]Type{
		"Error":	TypeOf((*pkg.Error)(nil)).Elem(),
		"EscapeError":	TypeOf((*pkg.EscapeError)(nil)).Elem(),
		"InvalidHostError":	TypeOf((*pkg.InvalidHostError)(nil)).Elem(),
		"URL":	TypeOf((*pkg.URL)(nil)).Elem(),
		"Userinfo":	TypeOf((*pkg.Userinfo)(nil)).Elem(),
		"Values":	TypeOf((*pkg.Values)(nil)).Elem(),
	}
}
