// this file was generated by gomacro command: import "net/http/httptrace"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	"net/http/httptrace"
)

func init() {
	Binds["net/http/httptrace"] = map[string]Value{
		"ContextClientTrace":	ValueOf(httptrace.ContextClientTrace),
		"WithClientTrace":	ValueOf(httptrace.WithClientTrace),
	}
	Types["net/http/httptrace"] = map[string]Type{
		"ClientTrace":	TypeOf((*httptrace.ClientTrace)(nil)).Elem(),
		"DNSDoneInfo":	TypeOf((*httptrace.DNSDoneInfo)(nil)).Elem(),
		"DNSStartInfo":	TypeOf((*httptrace.DNSStartInfo)(nil)).Elem(),
		"GotConnInfo":	TypeOf((*httptrace.GotConnInfo)(nil)).Elem(),
		"WroteRequestInfo":	TypeOf((*httptrace.WroteRequestInfo)(nil)).Elem(),
	}
	Proxies["net/http/httptrace"] = map[string]Type{
	}
}
