// this file was generated by gomacro command: import "net/rpc/jsonrpc"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "net/rpc/jsonrpc"
	. "reflect"
)

func init() {
	Binds["net/rpc/jsonrpc"] = map[string]Value{
		"Dial":	ValueOf(pkg.Dial),
		"NewClient":	ValueOf(pkg.NewClient),
		"NewClientCodec":	ValueOf(pkg.NewClientCodec),
		"NewServerCodec":	ValueOf(pkg.NewServerCodec),
		"ServeConn":	ValueOf(pkg.ServeConn),
	}
	Types["net/rpc/jsonrpc"] = map[string]Type{
	}
}
