// this file was generated by gomacro command: import "net/http/cgi"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	"net/http/cgi"
)

func init() {
	Binds["net/http/cgi"] = map[string]Value{
		"Request":	ValueOf(cgi.Request),
		"RequestFromMap":	ValueOf(cgi.RequestFromMap),
		"Serve":	ValueOf(cgi.Serve),
	}
	Types["net/http/cgi"] = map[string]Type{
		"Handler":	TypeOf((*cgi.Handler)(nil)).Elem(),
	}
	Proxies["net/http/cgi"] = map[string]Type{
	}
}
