// this file was generated by gomacro command: import "net/url"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	"net/url"
)

func init() {
	Binds["net/url"] = map[string]Value{
		"Parse":	ValueOf(url.Parse),
		"ParseQuery":	ValueOf(url.ParseQuery),
		"ParseRequestURI":	ValueOf(url.ParseRequestURI),
		"PathEscape":	ValueOf(url.PathEscape),
		"PathUnescape":	ValueOf(url.PathUnescape),
		"QueryEscape":	ValueOf(url.QueryEscape),
		"QueryUnescape":	ValueOf(url.QueryUnescape),
		"User":	ValueOf(url.User),
		"UserPassword":	ValueOf(url.UserPassword),
	}
	Types["net/url"] = map[string]Type{
		"Error":	TypeOf((*url.Error)(nil)).Elem(),
		"EscapeError":	TypeOf((*url.EscapeError)(nil)).Elem(),
		"InvalidHostError":	TypeOf((*url.InvalidHostError)(nil)).Elem(),
		"URL":	TypeOf((*url.URL)(nil)).Elem(),
		"Userinfo":	TypeOf((*url.Userinfo)(nil)).Elem(),
		"Values":	TypeOf((*url.Values)(nil)).Elem(),
	}
	Proxies["net/url"] = map[string]Type{
	}
}
