// this file was generated by gomacro command: import "net/textproto"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	"net/textproto"
)

func init() {
	Binds["net/textproto"] = map[string]Value{
		"CanonicalMIMEHeaderKey":	ValueOf(textproto.CanonicalMIMEHeaderKey),
		"Dial":	ValueOf(textproto.Dial),
		"NewConn":	ValueOf(textproto.NewConn),
		"NewReader":	ValueOf(textproto.NewReader),
		"NewWriter":	ValueOf(textproto.NewWriter),
		"TrimBytes":	ValueOf(textproto.TrimBytes),
		"TrimString":	ValueOf(textproto.TrimString),
	}
	Types["net/textproto"] = map[string]Type{
		"Conn":	TypeOf((*textproto.Conn)(nil)).Elem(),
		"Error":	TypeOf((*textproto.Error)(nil)).Elem(),
		"MIMEHeader":	TypeOf((*textproto.MIMEHeader)(nil)).Elem(),
		"Pipeline":	TypeOf((*textproto.Pipeline)(nil)).Elem(),
		"ProtocolError":	TypeOf((*textproto.ProtocolError)(nil)).Elem(),
		"Reader":	TypeOf((*textproto.Reader)(nil)).Elem(),
		"Writer":	TypeOf((*textproto.Writer)(nil)).Elem(),
	}
	Proxies["net/textproto"] = map[string]Type{
	}
}
