// this file was generated by gomacro command: import "net/textproto"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "net/textproto"
	. "reflect"
)

func init() {
	Binds["net/textproto"] = map[string]Value{
		"CanonicalMIMEHeaderKey":	ValueOf(pkg.CanonicalMIMEHeaderKey),
		"Dial":	ValueOf(pkg.Dial),
		"NewConn":	ValueOf(pkg.NewConn),
		"NewReader":	ValueOf(pkg.NewReader),
		"NewWriter":	ValueOf(pkg.NewWriter),
		"TrimBytes":	ValueOf(pkg.TrimBytes),
		"TrimString":	ValueOf(pkg.TrimString),
	}
	Types["net/textproto"] = map[string]Type{
		"Conn":	TypeOf((*pkg.Conn)(nil)).Elem(),
		"Error":	TypeOf((*pkg.Error)(nil)).Elem(),
		"MIMEHeader":	TypeOf((*pkg.MIMEHeader)(nil)).Elem(),
		"Pipeline":	TypeOf((*pkg.Pipeline)(nil)).Elem(),
		"ProtocolError":	TypeOf((*pkg.ProtocolError)(nil)).Elem(),
		"Reader":	TypeOf((*pkg.Reader)(nil)).Elem(),
		"Writer":	TypeOf((*pkg.Writer)(nil)).Elem(),
	}
}
