// this file was generated by gomacro command: import "net/http/pprof"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	"net/http/pprof"
)

func init() {
	Binds["net/http/pprof"] = map[string]Value{
		"Cmdline":	ValueOf(pprof.Cmdline),
		"Handler":	ValueOf(pprof.Handler),
		"Index":	ValueOf(pprof.Index),
		"Profile":	ValueOf(pprof.Profile),
		"Symbol":	ValueOf(pprof.Symbol),
		"Trace":	ValueOf(pprof.Trace),
	}
	Types["net/http/pprof"] = map[string]Type{
	}
	Proxies["net/http/pprof"] = map[string]Type{
	}
}
