// this file was generated by gomacro command: import _b "net/http/fcgi"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	"net/http/fcgi"
	. "reflect"
)

// reflection: allow interpreted code to import "net/http/fcgi"
func init() {
	Packages["net/http/fcgi"] = Package{
		Binds: map[string]Value{
			"ErrConnClosed":     ValueOf(&fcgi.ErrConnClosed).Elem(),
			"ErrRequestAborted": ValueOf(&fcgi.ErrRequestAborted).Elem(),
			"ProcessEnv":        ValueOf(fcgi.ProcessEnv),
			"Serve":             ValueOf(fcgi.Serve),
		},
	}
}
