// this file was generated by gomacro command: import "os/exec"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	"os/exec"
)

func init() {
	Packages["os/exec"] = Package{
	Binds: map[string]Value{
		"Command":	ValueOf(exec.Command),
		"CommandContext":	ValueOf(exec.CommandContext),
		"ErrNotFound":	ValueOf(&exec.ErrNotFound).Elem(),
		"LookPath":	ValueOf(exec.LookPath),
	},
	Types: map[string]Type{
		"Cmd":	TypeOf((*exec.Cmd)(nil)).Elem(),
		"Error":	TypeOf((*exec.Error)(nil)).Elem(),
		"ExitError":	TypeOf((*exec.ExitError)(nil)).Elem(),
	},
	Proxies: map[string]Type{
	} }
}
