// this file was generated by gomacro command: import "os/exec"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "os/exec"
	. "reflect"
)

func init() {
	Binds["os/exec"] = map[string]Value{
		"Command":	ValueOf(pkg.Command),
		"CommandContext":	ValueOf(pkg.CommandContext),
		"ErrNotFound":	ValueOf(&pkg.ErrNotFound).Elem(),
		"LookPath":	ValueOf(pkg.LookPath),
	}
	Types["os/exec"] = map[string]Type{
		"Cmd":	TypeOf((*pkg.Cmd)(nil)).Elem(),
		"Error":	TypeOf((*pkg.Error)(nil)).Elem(),
		"ExitError":	TypeOf((*pkg.ExitError)(nil)).Elem(),
	}
}
