// this file was generated by gomacro command: import "os/signal"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "os/signal"
	. "reflect"
)

func Package_os_signal() (map[string]Value, map[string]Type) {
	return map[string]Value{
			"Ignore": ValueOf(pkg.Ignore),
			"Notify": ValueOf(pkg.Notify),
			"Reset":  ValueOf(pkg.Reset),
			"Stop":   ValueOf(pkg.Stop),
		}, map[string]Type{}
}

func init() {
	binds, types := Package_os_signal()
	Binds["os/signal"] = binds
	Types["os/signal"] = types
}
