// this file was generated by gomacro command: import "path"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "path"
	. "reflect"
)

func init() {
	Binds["path"] = map[string]Value{
		"Base":	ValueOf(pkg.Base),
		"Clean":	ValueOf(pkg.Clean),
		"Dir":	ValueOf(pkg.Dir),
		"ErrBadPattern":	ValueOf(&pkg.ErrBadPattern).Elem(),
		"Ext":	ValueOf(pkg.Ext),
		"IsAbs":	ValueOf(pkg.IsAbs),
		"Join":	ValueOf(pkg.Join),
		"Match":	ValueOf(pkg.Match),
		"Split":	ValueOf(pkg.Split),
	}
	Types["path"] = map[string]Type{
	}
}
