// this file was generated by gomacro command: import "plugin"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "plugin"
	. "reflect"
)

func init() {
	Binds["plugin"] = map[string]Value{
		"Open":	ValueOf(pkg.Open),
	}
	Types["plugin"] = map[string]Type{
		"Plugin":	TypeOf((*pkg.Plugin)(nil)).Elem(),
		"Symbol":	TypeOf((*pkg.Symbol)(nil)).Elem(),
	}
}
