// this file was generated by gomacro command: import "regexp"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	"regexp"
)

func init() {
	Binds["regexp"] = map[string]Value{
		"Compile":	ValueOf(regexp.Compile),
		"CompilePOSIX":	ValueOf(regexp.CompilePOSIX),
		"Match":	ValueOf(regexp.Match),
		"MatchReader":	ValueOf(regexp.MatchReader),
		"MatchString":	ValueOf(regexp.MatchString),
		"MustCompile":	ValueOf(regexp.MustCompile),
		"MustCompilePOSIX":	ValueOf(regexp.MustCompilePOSIX),
		"QuoteMeta":	ValueOf(regexp.QuoteMeta),
	}
	Types["regexp"] = map[string]Type{
		"Regexp":	TypeOf((*regexp.Regexp)(nil)).Elem(),
	}
	Proxies["regexp"] = map[string]Type{
	}
}
