// this file was generated by gomacro command: import "runtime/pprof"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	"runtime/pprof"
)

func init() {
	Binds["runtime/pprof"] = map[string]Value{
		"Lookup":	ValueOf(pprof.Lookup),
		"NewProfile":	ValueOf(pprof.NewProfile),
		"Profiles":	ValueOf(pprof.Profiles),
		"StartCPUProfile":	ValueOf(pprof.StartCPUProfile),
		"StopCPUProfile":	ValueOf(pprof.StopCPUProfile),
		"WriteHeapProfile":	ValueOf(pprof.WriteHeapProfile),
	}
	Types["runtime/pprof"] = map[string]Type{
		"Profile":	TypeOf((*pprof.Profile)(nil)).Elem(),
	}
	Proxies["runtime/pprof"] = map[string]Type{
	}
}
