// this file was generated by gomacro command: import "runtime/debug"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "runtime/debug"
	. "reflect"
)

func init() {
	Binds["runtime/debug"] = map[string]Value{
		"FreeOSMemory":	ValueOf(pkg.FreeOSMemory),
		"PrintStack":	ValueOf(pkg.PrintStack),
		"ReadGCStats":	ValueOf(pkg.ReadGCStats),
		"SetGCPercent":	ValueOf(pkg.SetGCPercent),
		"SetMaxStack":	ValueOf(pkg.SetMaxStack),
		"SetMaxThreads":	ValueOf(pkg.SetMaxThreads),
		"SetPanicOnFault":	ValueOf(pkg.SetPanicOnFault),
		"SetTraceback":	ValueOf(pkg.SetTraceback),
		"Stack":	ValueOf(pkg.Stack),
		"WriteHeapDump":	ValueOf(pkg.WriteHeapDump),
	}
	Types["runtime/debug"] = map[string]Type{
		"GCStats":	TypeOf((*pkg.GCStats)(nil)).Elem(),
	}
}
