// this file was generated by gomacro command: import "runtime/pprof"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	pkg "runtime/pprof"
)

func Package_runtime_pprof() (map[string]Value, map[string]Type) {
	return map[string]Value{
			"Lookup":           ValueOf(pkg.Lookup),
			"NewProfile":       ValueOf(pkg.NewProfile),
			"Profiles":         ValueOf(pkg.Profiles),
			"StartCPUProfile":  ValueOf(pkg.StartCPUProfile),
			"StopCPUProfile":   ValueOf(pkg.StopCPUProfile),
			"WriteHeapProfile": ValueOf(pkg.WriteHeapProfile),
		}, map[string]Type{
			"Profile": TypeOf((*pkg.Profile)(nil)).Elem(),
		}
}

func init() {
	binds, types := Package_runtime_pprof()
	Binds["runtime/pprof"] = binds
	Types["runtime/pprof"] = types
}
