// this file was generated by gomacro command: import "runtime/trace"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "runtime/trace"
	. "reflect"
)

func init() {
	Binds["runtime/trace"] = map[string]Value{
		"Start":	ValueOf(pkg.Start),
		"Stop":	ValueOf(pkg.Stop),
	}
	Types["runtime/trace"] = map[string]Type{
	}
}
