// this file was generated by gomacro command: import _b "runtime/metrics"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	metrics "runtime/metrics"
)

// reflection: allow interpreted code to import "runtime/metrics"
func init() {
	Packages["runtime/metrics"] = Package{
		Name: "metrics",
		Binds: map[string]Value{
			"All":	ValueOf(metrics.All),
			"KindBad":	ValueOf(metrics.KindBad),
			"KindFloat64":	ValueOf(metrics.KindFloat64),
			"KindFloat64Histogram":	ValueOf(metrics.KindFloat64Histogram),
			"KindUint64":	ValueOf(metrics.KindUint64),
			"Read":	ValueOf(metrics.Read),
		}, Types: map[string]Type{
			"Description":	TypeOf((*metrics.Description)(nil)).Elem(),
			"Float64Histogram":	TypeOf((*metrics.Float64Histogram)(nil)).Elem(),
			"Sample":	TypeOf((*metrics.Sample)(nil)).Elem(),
			"Value":	TypeOf((*metrics.Value)(nil)).Elem(),
			"ValueKind":	TypeOf((*metrics.ValueKind)(nil)).Elem(),
		}, 
	}
}
