// this file was generated by gomacro command: import _b "testing/fstest"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	fstest "testing/fstest"
)

// reflection: allow interpreted code to import "testing/fstest"
func init() {
	Packages["testing/fstest"] = Package{
		Name: "fstest",
		Binds: map[string]Value{
			"TestFS":	ValueOf(fstest.TestFS),
		}, Types: map[string]Type{
			"MapFS":	TypeOf((*fstest.MapFS)(nil)).Elem(),
			"MapFile":	TypeOf((*fstest.MapFile)(nil)).Elem(),
		}, 
	}
}
