// this file was generated by gomacro command: import "text/scanner"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	"text/scanner"
)

func init() {
	Packages["text/scanner"] = Package{
	Binds: map[string]Value{
		"Char":	ValueOf(scanner.Char),
		"Comment":	ValueOf(scanner.Comment),
		"EOF":	ValueOf(scanner.EOF),
		"Float":	ValueOf(scanner.Float),
		"GoTokens":	ValueOf(scanner.GoTokens),
		"GoWhitespace":	ValueOf(int64(scanner.GoWhitespace)),
		"Ident":	ValueOf(scanner.Ident),
		"Int":	ValueOf(scanner.Int),
		"RawString":	ValueOf(scanner.RawString),
		"ScanChars":	ValueOf(scanner.ScanChars),
		"ScanComments":	ValueOf(scanner.ScanComments),
		"ScanFloats":	ValueOf(scanner.ScanFloats),
		"ScanIdents":	ValueOf(scanner.ScanIdents),
		"ScanInts":	ValueOf(scanner.ScanInts),
		"ScanRawStrings":	ValueOf(scanner.ScanRawStrings),
		"ScanStrings":	ValueOf(scanner.ScanStrings),
		"SkipComments":	ValueOf(scanner.SkipComments),
		"String":	ValueOf(scanner.String),
		"TokenString":	ValueOf(scanner.TokenString),
	},
	Types: map[string]Type{
		"Position":	TypeOf((*scanner.Position)(nil)).Elem(),
		"Scanner":	TypeOf((*scanner.Scanner)(nil)).Elem(),
	},
	Proxies: map[string]Type{
	} }
}
