// this file was generated by gomacro command: import "text/tabwriter"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	pkg "text/tabwriter"
)

func Package_text_tabwriter() (map[string]Value, map[string]Type) {
	return map[string]Value{
			"AlignRight":          ValueOf(pkg.AlignRight),
			"Debug":               ValueOf(pkg.Debug),
			"DiscardEmptyColumns": ValueOf(pkg.DiscardEmptyColumns),
			"Escape":              ValueOf(pkg.Escape),
			"FilterHTML":          ValueOf(pkg.FilterHTML),
			"NewWriter":           ValueOf(pkg.NewWriter),
			"StripEscape":         ValueOf(pkg.StripEscape),
			"TabIndent":           ValueOf(pkg.TabIndent),
		}, map[string]Type{
			"Writer": TypeOf((*pkg.Writer)(nil)).Elem(),
		}
}

func init() {
	binds, types := Package_text_tabwriter()
	Binds["text/tabwriter"] = binds
	Types["text/tabwriter"] = types
}
