// this file was generated by gomacro command: import "text/tabwriter"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "text/tabwriter"
	. "reflect"
)

func init() {
	Binds["text/tabwriter"] = map[string]Value{
		"AlignRight":	ValueOf(pkg.AlignRight),
		"Debug":	ValueOf(pkg.Debug),
		"DiscardEmptyColumns":	ValueOf(pkg.DiscardEmptyColumns),
		"Escape":	ValueOf(pkg.Escape),
		"FilterHTML":	ValueOf(pkg.FilterHTML),
		"NewWriter":	ValueOf(pkg.NewWriter),
		"StripEscape":	ValueOf(pkg.StripEscape),
		"TabIndent":	ValueOf(pkg.TabIndent),
	}
	Types["text/tabwriter"] = map[string]Type{
		"Writer":	TypeOf((*pkg.Writer)(nil)).Elem(),
	}
}
