// this file was generated by gomacro command: import "unicode/utf8"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	pkg "unicode/utf8"
	. "reflect"
)

func init() {
	Binds["unicode/utf8"] = map[string]Value{
		"DecodeLastRune":	ValueOf(pkg.DecodeLastRune),
		"DecodeLastRuneInString":	ValueOf(pkg.DecodeLastRuneInString),
		"DecodeRune":	ValueOf(pkg.DecodeRune),
		"DecodeRuneInString":	ValueOf(pkg.DecodeRuneInString),
		"EncodeRune":	ValueOf(pkg.EncodeRune),
		"FullRune":	ValueOf(pkg.FullRune),
		"FullRuneInString":	ValueOf(pkg.FullRuneInString),
		"MaxRune":	ValueOf(pkg.MaxRune),
		"RuneCount":	ValueOf(pkg.RuneCount),
		"RuneCountInString":	ValueOf(pkg.RuneCountInString),
		"RuneError":	ValueOf(pkg.RuneError),
		"RuneLen":	ValueOf(pkg.RuneLen),
		"RuneSelf":	ValueOf(pkg.RuneSelf),
		"RuneStart":	ValueOf(pkg.RuneStart),
		"UTFMax":	ValueOf(pkg.UTFMax),
		"Valid":	ValueOf(pkg.Valid),
		"ValidRune":	ValueOf(pkg.ValidRune),
		"ValidString":	ValueOf(pkg.ValidString),
	}
	Types["unicode/utf8"] = map[string]Type{
	}
}
