// this file was generated by gomacro command: import "unicode/utf16"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	"unicode/utf16"
)

func init() {
	Binds["unicode/utf16"] = map[string]Value{
		"Decode":	ValueOf(utf16.Decode),
		"DecodeRune":	ValueOf(utf16.DecodeRune),
		"Encode":	ValueOf(utf16.Encode),
		"EncodeRune":	ValueOf(utf16.EncodeRune),
		"IsSurrogate":	ValueOf(utf16.IsSurrogate),
	}
	Types["unicode/utf16"] = map[string]Type{
	}
	Proxies["unicode/utf16"] = map[string]Type{
	}
}
