// this file was generated by gomacro command: import "unsafe"
// DO NOT EDIT! Any change will be lost when the file is re-generated

package imports

import (
	. "reflect"
	"unsafe"
)

func init() {
	Packages["unsafe"] = Package{
	Binds: map[string]Value{
	},
	Types: map[string]Type{
		"Pointer":	TypeOf((*unsafe.Pointer)(nil)).Elem(),
	},
	Proxies: map[string]Type{
	} }
}
